### ISSUE TITLE
Problem with dmaker.fan.1c

### ISSUE THREAD

**Issue by olskar** [rytilahti/python-miio#1036]
**Describe the bug**
Delighted to see support for dmaker.fan.1c in 0.5.6, however it seems to be a problem, not sure if it is a problem on my end or not?

**Version information (please complete the following information):**
 - OS: Linux
 - python-miio: 0.5.6

**Device information:**
Mi Smart Standing Fan 1C

**To Reproduce**
1. miiocli -d fan --ip 192.168.1.162 --token XXXXXXXXXXXXXXXXXX status 

**Expected behavior**
Controlling the fan

**Console output**
```
miiocli -d fan --ip 192.168.1.162 --token XXXXXXXXXXXXXXXXXX status 
INFO:miio.cli:Debug mode active
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x0eEW\x0c\x00\x04c|' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('0e45570c')
            ts = 1970-01-04 07:53:32
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 0e45570c with ts: 1970-01-04 07:53:32, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.162:54321 >>: {'id': 1, 'method': 'get_prop', 'params': ['temp_dec', 'humidity', 'battery', 'bat_charge', 'button_pressed', 'angle', 'speed', 'poweroff_time', 'power', 'ac_power', 'angle_enable', 'speed_level', 'natural_level', 'child_lock', 'buzzer']}
DEBUG:miio.miioprotocol:192.168.1.162:54321 (ts: 1970-01-04 07:53:36, id: 1) << {'id': 1, 'error': {'code': -9999, 'message': 'user ack timeout'}}
DEBUG:miio.click_common:Exception: {'code': -9999, 'message': 'user ack timeout'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/fan.py", line 323, in status
    values = self.get_properties(properties, max_properties=_props_per_request)
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 269, in get_properties
    values.extend(self.send(property_getter, _props[:max_properties]))
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.8/site-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -9999, 'message': 'user ack timeout'}
Error: {'code': -9999, 'message': 'user ack timeout'}
```

**Comment by syssi** [comment]
@olskar Could you test all features of the implementation **please** :-) and provide some feedback?

**Comment by olskar** [comment]
> @olskar Could you test all features of the implementation **please** :-) and provide some feedback?

I tested most of them and everything works fine @syssi  :)
