### ISSUE TITLE
Xiaomi WiFi Speaker not running

### ISSUE THREAD

**Issue by ZencoreCZ** [rytilahti/python-miio#1097]
Hello, where I have a problem? **Error: Unable to discover the device 192.168.0.203**
I have Mi Wifi Speaker.
Thanks Lukas
```
Lukas@raspberrypi:~ $ miiocli wifispeaker info
Usage: miiocli wifispeaker [OPTIONS] COMMAND [ARGS]...
Try 'miiocli wifispeaker --help' for help.

Error: Missing option '--ip'.
Lukas@raspberrypi:~ $ miiocli device --ip 192.168.0.203 --token b16f4ef9dfde8faf26f7fa26dfb454fc status
Usage: miiocli device [OPTIONS] COMMAND [ARGS]...
Try 'miiocli device --help' for help.

Error: Unknown command (status)
Lukas@raspberrypi:~ $ miiocli device --ip 192.168.0.203 --token b16f4ef9dfde8faf26f7fa26dfb454fc info
**Error: Unable to discover the device 192.168.0.203**

Lukas@raspberrypi:~ $ miiocli --debug device --ip 192.168.0.203 --token b16f4ef9dfde8faf26f7fa26dfb454fc info
INFO:miio.cli:Debug mode active
DEBUG:miio.miioprotocol:Unable to discover a device at address 192.168.0.203
DEBUG:miio.click_common:Exception: Unable to discover the device 192.168.0.203
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/device.py", line 214, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.7/dist-packages/miio/device.py", line 179, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/usr/local/lib/python3.7/dist-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.7/dist-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.0.203
**Error: Unable to discover the device 192.168.0.203**

```

**Comment by rytilahti** [comment]
It may very well be that the newer versions of the speaker are not using the same protocol. The device I had when writing the support looked like this: 
![image](https://user-images.githubusercontent.com/3705853/129245591-d87ec11c-ccd8-4250-a5ba-474ea228b824.png)

**Comment by ZencoreCZ** [comment]
Too bad.
Now: [https://im9.cz/iR/importprodukt-orig/595/5951484c85be236d4a37e7794956c721--mmf1000x1000.jpg](url)
