### ISSUE TITLE
Flashing fails because of "Unable to parse message payload"

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [rytilahti/python-miio#1103]
Hi, I just tried flashing my rockrobo.vacuum.v1, but it fails because of an seemingly empty response?

```
$ mirobo -d --token 686a755a7a375173314172456637356b --ip 192.168.8.1 update-firmware ~/Downloads/v11_004018.pkg 
INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Read stored sequence ids: {'seq': 203, 'manual_seq': 0}
DEBUG:miio.vacuum_cli:Connecting to 192.168.8.1 with token 686a755a7a375173314172456637356b
Going to update from /home/feedc0de/Downloads/v11_004018.pkg
INFO:miio.updater:Serving on 0.0.0.0:40753, timeout 10
INFO:miio.updater:Using local /home/feedc0de/Downloads/v11_004018.pkg (md5: dd5a0cb4dfe2e003cd6398323efdc5a8)
DEBUG:miio.updater:available interfaces: ['enp2s0f0', 'wlan0', 'virbr0', 'wg0', 'docker0']
DEBUG:miio.updater:enp2s0f0 has no ipv4 addresses, skipping
DEBUG:miio.updater:Got addr: 192.168.8.188
Hosting file at http://192.168.8.188:40753/v11_004018.pkg
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x13\x17\x83\xd5\x00\x00eH' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('131783d5')
            ts = 1970-01-01 07:12:08
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'hjuZz7Qs1ArEf75k' (total 16)
DEBUG:miio.miioprotocol:Discovered 131783d5 with ts: 1970-01-01 07:12:08, token: b'686a755a7a375173314172456637356b'
DEBUG:miio.miioprotocol:192.168.8.1:54321 >>: {'id': 204, 'method': 'miIO.ota', 'params': {'mode': 'normal', 'install': '1', 'app_url': 'http://192.168.8.188:40753/v11_004018.pkg', 'file_md5': 'dd5a0cb4dfe2e003cd6398323efdc5a8', 'proc': 'dnld install'}}
DEBUG:miio.protocol:Unable to parse json '': Expecting value: line 1 column 1 (char 0)
DEBUG:miio.click_common:Exception: Unable to parse message payload
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/miio/protocol.py", line 198, in _decode
    return json.loads(decoded)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/miio/vacuum_cli.py", line 620, in update_firmware
    update_res = vac.update(url, md5)
  File "/usr/lib/python3.9/site-packages/miio/device.py", line 234, in update
    return self.send("miIO.ota", payload)[0] == "ok"
  File "/usr/lib/python3.9/site-packages/miio/device.py", line 178, in send
    return self._protocol.send(
  File "/usr/lib/python3.9/site-packages/miio/miioprotocol.py", line 194, in send
    m = Message.parse(data, token=self.token)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 2653, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 4295, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 4598, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.9/site-packages/construct/core.py", line 704, in _parse
    return self._decode(obj, context, path)
  File "/usr/lib/python3.9/site-packages/miio/protocol.py", line 204, in _decode
    raise PayloadDecodeException(
miio.exceptions.PayloadDecodeException: Unable to parse message payload
Error: Unable to parse message payload
ERROR:miio.updater:No request was made..
```

**Comment by Dwosky** [comment]
I had more or less the same issue with a v2 (S5) model. The final error was the same, `Error: Unable to parse message payload` and running it with `--debug` stated that there might be an issue with the JSON itself.

On my case, since the vacuum was recently updated, I did a factory reset to revert it to stock, tried again and it worked without issues. I think someone pointed that new oficial firmwares might be blocking this kind of updates.

**Comment by tegger2000** [comment]
A little tip with the factory reset. There are different instructions online. In my case, I need to press the reset button only 1 short time, after pressing the home (plug) button 4 sec. before. The interval of the blue blinking light is changing next to the reset button. During short press of reset button, don't release the home button, then there was the factory reset in my case.

**Comment by rytilahti** [comment]
Please reopen this with more details about the issue if it is still valid.
