### ISSUE TITLE
miotdevice command throws error with all options

### ISSUE THREAD

**Issue by blakadder** [rytilahti/python-miio#1118]
**Describe the bug**
when trying to use `miotdevice` it throws an error "Error: Neither the class nor the parameter defines the mapping" when trying to use any of the available options

**Version information (please complete the following information):**
 - OS: Win10
 - python-miio:miiocli, version 0.5.7

**To Reproduce**
1. use command `miiocli miotdevice --ip <ip> --token <token> info`

**Expected behavior**
Execution of the command

When using other xxmiot commands such as `fanmiot` or `heatermiot` executes commands with no errors

**Console output**

```
 miiocli -d miotdevice --ip 10.1.1.17 --token <hidden> info
INFO:miio.cli:Debug mode active
DEBUG:miio.click_common:Exception: Neither the class nor the parameter defines the mapping
Traceback (most recent call last):
  File "d:\python37\lib\site-packages\miio\click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "d:\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python37\lib\site-packages\click\core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "d:\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\python37\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\python37\lib\site-packages\miio\click_common.py", line 242, in group_callback
    ctx.obj = self.device_class(*args, **kwargs)
  File "d:\python37\lib\site-packages\miio\miot_device.py", line 51, in __init__
    "Neither the class nor the parameter defines the mapping"
miio.exceptions.DeviceException: Neither the class nor the parameter defines the mapping
Error: Neither the class nor the parameter defines the mapping
```

**Comment by rytilahti** [comment]
This is related to #1085
