### ISSUE TITLE
Support for airhumidifiercb1?

### ISSUE THREAD

**Issue by artur5236** [rytilahti/python-miio#1199]
miiocli -d airhumidifiercb1 --ip 192.168.5.91 --token xxx status
Result:

INFO:miio.cli:Debug mode active
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 10, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 63, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 270, in group_callback
    ctx.obj = self.device_class(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'model'

Name: python-miio
Version: 0.5.9

**Comment by rytilahti** [comment]
I think this is a regression. Could you try if `miiocli airhumidifier --ip 192.168.5.91 --token xxx status` or `miiocli airhumidifier --ip 192.168.5.91 --token xxx --model zhimi.humidifier.cb1 status` are working fine for you?

**Comment by artur5236** [comment]
Thank you. miiocli airhumidifier --ip 192.168.5.91 --token xxx status working fine.

**Comment by rytilahti** [comment]
Great! Let's keep this still open as it's clearly a bug.

**Comment by artur5236** [comment]
I get below warning:
WARNING:miio.device:Found an unsupported model 'zhimi.humidifier.cb1' for class 'AirHumidifier'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio
