### ISSUE TITLE
unsupported model 'philips.light.downlight' for class 'PhilipsBulb'

### ISSUE THREAD

**Issue by zvldz** [rytilahti/python-miio#1211]
**Describe the bug**
After updating Home Assistant to version 2021.12.0b1, errors appeared in the logs.
```
2021-12-06 11:40:31 WARNING (SyncWorker_6) [miio.device] Found an unsupported model 'philips.light.downlight' for class 'PhilipsBulb'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2021-12-06 11:40:31 WARNING (SyncWorker_0) [miio.device] Found an unsupported model 'philips.light.downlight' for class 'PhilipsBulb'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2021-12-06 11:40:31 WARNING (SyncWorker_2) [miio.device] Found an unsupported model 'philips.light.downlight' for class 'PhilipsBulb'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2021-12-06 11:40:31 WARNING (SyncWorker_7) [miio.device] Found an unsupported model 'philips.light.downlight' for class 'PhilipsBulb'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
...
2021-12-06 11:40:33 ERROR (MainThread) [homeassistant.components.light] xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 502, in async_update
    self._color_temp = self.translate(
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 521, in translate
    value_scaled = float(value - left_min) / float(left_span)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: philips.light.downlight (Xiaomi Philips Zhirui Smart Downlight)
  - Hardware version:
  - Firmware version:

**To Reproduce**
1. install Home Assistant 2021.12.0b1

**Expected behavior**

**Console output**
If applicable, add console output to help explain your problem.
If the issue is about communication with a specific device, consider including the output using the `--debug` flag.

**Comment by rytilahti** [comment]
Looks like that the device is reporting the color temperature as `None`.

Could you enable debug logging to `miio` and check the response from the device? Or alternatively, you can install python-miio locally and execute `miiocli --debug philipsbulb --ip <addr> --token <token> status`.

**Comment by zvldz** [comment]
Home Assistant debugging logs
https://pastebin.com/yXpmCght

**Comment by rytilahti** [comment]
I don't see that `TypeError` with `unsupported operand type` in the homeassistant logs, and the output from miiocli looks correct also on the color temperature value, so I'm not sure what is wrong there.

**Comment by zvldz** [comment]
I edited philips_bulb.py manually, but this error remains
```
2021-12-06 20:32:52 ERROR (MainThread) [homeassistant.components.light] xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 502, in async_update
    self._color_temp = self.translate(
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 521, in translate
    value_scaled = float(value - left_min) / float(left_span)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by rytilahti** [comment]
Please take a look at the log just above it, does the response (this part `'result': ['off', 0, 50, 50, 0],`) look similar to that what you posted above?

**Comment by zvldz** [comment]
I understand that this is a different kind of error.
But you "codeowners" of the xiaomi_miio component.

**Comment by zvldz** [comment]
Here is the answer from miiocli inside the home assistant container:
```
bash-5.1# miiocli --debug philipsbulb --ip 192.168.1.24 --token xxxYYYXXX status
INFO:miio.cli:Debug mode active
DEBUG:miio.click_common:Unknown model, trying autodetection. None None
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x04H\xc4\x02\x00\x057\xe3' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('0448c402')
            ts = 1970-01-04 22:59:47
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
DEBUG:miio.miioprotocol:Discovered 0448c402 with ts: 1970-01-04 22:59:47, token: b'00000000000000000000000000000000'
DEBUG:miio.miioprotocol:192.168.1.24:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:192.168.1.24:54321 (ts: 1970-01-04 22:59:47, id: 1) << {'result': {'life': 341987, 'token': 'c562f1a58e59942d67fd6aa147f40ba6', 'mac': '78:11:DC:5A:86:35', 'fw_ver': '1.3.0_0021', 'hw_ver': 'ESP8266', 'uid': 1701801948, 'model': 'philips.light.downlight', 'wifi_fw_ver': '1.5.0-dev(7f7a714)', 'ap': {'rssi': -65, 'ssid': 'aiot', 'bssid': 'D6:CA:6D:93:EB:48'}, 'netif': {'localIp': '192.168.1.24', 'mask': '255.255.255.0', 'gw': '192.168.1.1'}, 'mmfree': 5728}, 'id': 1}
DEBUG:miio.device:Detected model philips.light.downlight
DEBUG:miio.miioprotocol:192.168.1.24:54321 >>: {'id': 2, 'method': 'get_prop', 'params': ['power', 'dv', 'bri']}
DEBUG:miio.miioprotocol:192.168.1.24:54321 (ts: 1970-01-04 22:59:47, id: 2) << {'result': ['off', 0, 50], 'id': 2}
Power: off
Brightness: 50
Delayed turn off: 0
Color temperature: None
Scene: None
```

**Comment by zvldz** [comment]
Possible fix:
```

**Comment by rytilahti** [comment]
Good catch, as there was no definition for available properties, it falls back to the defaults. The linked PR should fix this :-)

**Comment by zvldz** [comment]
If it's important, I'll check tomorrow and report back

**Comment by rytilahti** [comment]
No hurries, it will take some time anyway until it gets into a new release which gets into homeassistant. Feel free to re-open the issue if it is not working with the current master of python-miio.
