### ISSUE TITLE
roborock.vacuum.a14 not working without internet access

### ISSUE THREAD

**Issue by ivanman11** [rytilahti/python-miio#1213]
**Describe the bug**
I purchased a new vacuum - Roborock T7S and try to control it by HomeAssistant, and it working perfectly when the vacuum have internet access.
After I block the internet access of the vacuum, it not working any more, I did some study and try to change drop to reject in the firewall but still not working.
Is any method can make it work locally? Thanks for reading.

**Version information (please complete the following information):**
 - OS: CentOS 6
 - python-miio: 0.5.8

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: roborock.vacuum.a14
  - Hardware version: Linux
  - Firmware version: 4.1.2_1140
  
**To Reproduce**
1. Block the vacumm internet access
2. Try to access it by miiocli

**Expected behavior**
Success to control the vacumm locally

**Console output**

DEBUG:miio.vacuum:Read stored sequence ids: {'seq': 22, 'manual_seq': 0}
Running command status
DEBUG:miio.miioprotocol:Unable to discover a device at address 192.168.1.186
DEBUG:miio.click_common:Exception: Unable to discover the device 192.168.1.186
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/miio/vacuum.py", line 286, in status
    return VacuumStatus(self.send("get_status")[0])
  File "/usr/local/lib/python3.6/site-packages/miio/device.py", line 98, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/usr/local/lib/python3.6/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.6/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.186
Error: Unable to discover the device 192.168.1.186

**Comment by rytilahti** [comment]
Alas, I don't think there is a way to figure this out besides trying to test different firewall settings to see if that helps. I don't think these devices are rootable at the moment either.

**Comment by shred86** [comment]
Same issue on the Roborock S7. I’ve tried to reject outbound traffic but it results in constant connectivity issues in Home Assistant.

**Comment by ivanman11** [comment]
Finally it getting work after I root with DustBuilder firmware. If someone finding a solution can try it. (disassembly is needed, take your own risk)

**Comment by rytilahti** [comment]
I'll close this as there is nothing we can do to change the behavior of the original firmware (besides rooting and changing the firmware).
