### ISSUE TITLE
raw_command is not sent params fully

### ISSUE THREAD

**Issue by LennyLip** [rytilahti/python-miio#1221]
**Describe the bug**
--sendcmd lose parameter (without debug info)

**Version information (please complete the following information):**
 - OS: macos
 - python-miio (from pip3): 
```
 % (venv) miiocli --version
Traceback (most recent call last):
  File "/Users/user/tmp/venv/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/miio/cli.py", line 63, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1615, in parse_args
    rest = super().parse_args(ctx, args)
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/Users/user/tmp/venv/lib/python3.9/site-packages/click/decorators.py", line 380, in callback
    raise RuntimeError(
RuntimeError: 'miio' is not installed. Try passing 'package_name' instead.
```

**Device information:**
  - Model: lumi.gateway.v3

**To Reproduce**
```
% miiocli device --ip 192.168.1.21 --token xxxxx raw_command "set_channels" "{'chs':[{'id': 2048, 'type': 0, 'url':'http://live.ximalaya.com/radio-first-page-app/live/2564/64.m3u8'}]}"
Running command raw_command
['ok']
% miiocli device --ip 192.168.1.21 --token xxxxx raw_command "get_channels" "{'start':0}"
Running command raw_command
{'chs': [{'id': 2048, 'type': 0, 'url': ''}]}
```

**Expected behavior**
get_channels should return 
`{'chs': [{'id': 2048, 'type': 0, 'url': 'http://live.ximalaya.com/radio-first-page-app/live/2564/64.m3u8'}]}`

it looks like the URL does not send with the command

**php-miio**

php-miio works fine:

```
% php miio-cli.php --token xxxxx --ip 192.168.1.21  --sendcmd '{"id":10,"method":"set_channels","params":{"chs":[{"id":1023,"url":"http://live.xmcdn.com/live/1005/64.m3u8","type":0}]}}'
{"result":["ok"],"id":10}

% php miio-cli.php --token xxxxx --ip 192.168.1.21  --sendcmd '{"id":1, "method":"get_channels","params":{"start":0}}'
{"result":{"chs":[{"id":1023,"type":0,"url":"http:\/\/live.xmcdn.com\/live\/1005\/64.m3u8"}]},"id":1}
```

**Comment by rytilahti** [comment]
This looks similar to #629 but I don't have a solution at hand. The raw payloads likely differ causing this, which would require taking a deeper look into what exactly is being sent on the wire.

**Comment by LennyLip** [comment]
Hmm, yes, exactly the same thing. Sorry, I didn't see this issue early.
