### ISSUE TITLE
 Found an unsupported model 'philips.light.hbulb' for class 'Device'.

### ISSUE THREAD

**Issue by fereehu** [rytilahti/python-miio#1231]
After updating Home Assistant 2021.12 these devices stopped working. HA cannot connect to it. Before it was working fine.

**Device information:**

  - Name(s) of the device: **Xiaomi Philips Wi-Fi LED Bulb E27 (MUE4088RT)**

Use `miiocli device --ip <ip address> --token <token>`.

WARNING:miio.device:Found an unsupported model 'philips.light.hbulb' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

- Model: philips.light.hbulb
- Hardware version: ESP8266
- Firmware version: 1.3.7_0029

**Logs from HA**:
```
021-12-12 13:47:23 WARNING (SyncWorker_37) [miio.device] Found an unsupported model 'philips.light.hbulb' for class 'Device'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2021-12-12 13:47:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/config_flow.py", line 313, in async_step_manual
    return await self.async_step_connect()
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/config_flow.py", line 375, in async_step_connect
    await self.hass.config_entries.async_reload(existing_entry.entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 980, in async_reload
    unload_result = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 968, in async_unload
    raise OperationNotAllowed
homeassistant.config_entries.OperationNotAllowed
```

When removing and adding again from the UI with auto config: **The device model is not known, not able to setup the device using config flow.**
When manual config, the Device model (philips.light.hbulb) is not listed.

**Comment by rytilahti** [comment]
So I'm not yet sure what causes the issue with the device not working at all, the linked PR only silences the warning about an unknown model.

Looking at the homeassistant code, the code does not list that model nor does it use `PhilipsWhiteBulb` anywhere in the code, so I'm wondering what triggers the warning...

**Comment by fereehu** [comment]
@rytilahti i have modified `/usr/local/lib/python3.9/site-packages/miio/philips_bulb.py` to the master branches version, but not working (I'm using hassos, after editing the file, rebooted the host)

The Log details from HA when trying to manually add this philips hbulb:
```
Logger: homeassistant.config_entries
Source: components/xiaomi_miio/__init__.py:465
First occurred: 10:04:55 PM (1 occurrences)
Last logged: 10:04:55 PM

Error unloading entry philips.light.hbulb for xiaomi_miio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 452, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 465, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: '8cf521fd9ad4f214b3b43333c038e381'
```

And I'm not sure, if I already got this error before, but now I can see these:

```
2021-12-14 21:56:08 ERROR (MainThread) [homeassistant.components.light] xiaomi_miio: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
await task
File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 502, in async_update
self._color_temp = self.translate(
File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 521, in translate
value_scaled = float(value - left_min) / float(left_span)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by fereehu** [comment]
@rytilahti I'm using hass, but I could get a console via portainer. 
Steps which I did: 

- `pip install python-miio==0.5.9.2`
- rewrite the port to 8124 in HA config
- `python3 -m homeassistant --config /config`
- Logged in :8124
- Tried to add this philips hbulb in the integration-> Not in the list, just the other ones
- Log outputs are the same as before with TypeError

Maybe the above steps are not great for bumping/testing the versions, but couldn't do `hass --skip-pip`. Anyway, will try in the new HA release, maybe.

How could I help to determine what is the problem of the philips_hbulb? I would really need those lights to work.

**Comment by rytilahti** [comment]
@fereehu there's so many moving parts, so it's really hard to give any easy instructions how to test these. The simplest way I found myself is simply run another setup ("development setup") on a regular virtual environment for testing.

Was the bulb working previously, and what did you select back then for the model or was it autodetected? I never saw it listed explicitly inside homeassistant's codebase, so I'm wondering...

**Comment by fereehu** [comment]
@rytilahti Well, I have created a fresh install, downgraded to 2021.11.5 and to OS 6.6 (no idea if that is necessary, probably not).. but not working, these lights are not in the list.

If I remember correctly, I added those lights via yaml, and HA auto added the integration in release 2021.4. After I just deleted those yaml configs.
Tried to downgrade to 2021.3.1, but I think that was too much for the HA (only the onboarding screen is refreshing). But for 2021.4 I got the HA to work with downgrade.

From this point,the manually configured lights are working on 2021.4.1 (via yaml->auto added to UI), but I cannot add them via UI. And from 2021.11.5->2021.12.0 the manually added lights via yaml way back from <2021.3 are no longer working. So the problem is around 2021.4, not only with this release I think. 

Oh, btw: The model is `hbulb` or `bulb`? 
Because just rechecked the config, and the model was `philips.light.bulb` (but the `miiocli device` returned `philips.light.hbulb`.  (Tried with `bulb`, as it was in the list, but that doesn't work)

```
light:
  - platform: xiaomi_miio
    name: Light name
    host: 192.168.1.71
    token: <token>
    model: philips.light.bulb
```

These light does not support color temperature, only brightness.

**Comment by rytilahti** [comment]
Oh, thanks for bisecting! Hmm, this could be a separate problem then. There exists both `bulb` and `hbulb`, where the former supports color temperature. And looking [at the code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/const.py#L169), it seems that only brightness-only bulb is `philips.light.mono1`.. 

Could you try to modify that file to add your model to that list to see if it starts working? Or alternatively, select that mono1 as the model.

**Comment by fereehu** [comment]
With selecting mono1 it's working again, thank you! :) My main issue is gone with this. 
If `philips.light.mono1` would support these lights in the long run, it's good for me. Only need brightness control, but it's there, so for it seems everything is good. :)

**Comment by rytilahti** [comment]
Glad that it worked! :tada: 

So, the plan for the future is to automatically detect the implementation based on the model, so that's why that warning was logged. The hope is that it'll make it unnecessary to use custom components for anything that is already directly supported by python-miio & homeassistant (unknowingly, like in your case as homeassistant is missing this model information..).
