### ISSUE TITLE
Error: Unable to parse message payload

### ISSUE THREAD

**Issue by tegger2000** [rytilahti/python-miio#1289]
Hi,
I didn't get a modded firmware uploaded on a S5. I tried it with macOS, Raspbian,  and Ubuntu on Windows VMWare.
But i got same error on all devices, so this could be a bug

miio Version: 0.5.9.2
rockrobo.vacuum.v1 v1.0_dummy (None) @ 192.168.8.1 - token: 79685661557164536567484971456547
Software Version 2034

% mirobo --token 79685661557164536567484971456547 --ip 192.168.8.1 --debug update-firmware firmware/v11_002034.pkg
```
INFO:miio.integrations.vacuum.roborock.vacuum_cli:Debug mode active
DEBUG:miio.integrations.vacuum.roborock.vacuum_cli:Using config: {'seq': 208, 'manual_seq': 0}
DEBUG:miio.integrations.vacuum.roborock.vacuum_cli:Connecting to 192.168.8.1 with token 79685661557164536567484971456547
Going to update from firmware/v11_002034.pkg
INFO:miio.updater:Serving on 0.0.0.0:56030, timeout 10
INFO:miio.updater:Using local firmware/v11_002034.pkg (md5: c1312366b2b24e7f65ff698208aded8e)
DEBUG:miio.updater:available interfaces: ['gif0', 'stf0', 'anpi1', 'anpi0', 'en6', 'en7', 'en1', 'en2', 'ap1', 'en0', 'awdl0', 'llw0', 'bridge0', 'utun0', 'utun1', 'utun2']
DEBUG:miio.updater:gif0 has no ipv4 addresses, skipping
DEBUG:miio.updater:stf0 has no ipv4 addresses, skipping
DEBUG:miio.updater:anpi1 has no ipv4 addresses, skipping
DEBUG:miio.updater:anpi0 has no ipv4 addresses, skipping
DEBUG:miio.updater:en6 has no ipv4 addresses, skipping
DEBUG:miio.updater:en7 has no ipv4 addresses, skipping
DEBUG:miio.updater:en1 has no ipv4 addresses, skipping
DEBUG:miio.updater:en2 has no ipv4 addresses, skipping
DEBUG:miio.updater:ap1 has no ipv4 addresses, skipping
DEBUG:miio.updater:Got addr: 192.168.8.61
Hosting file at http://192.168.8.61:56030/v11_002034.pkg
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x05\xbf\r\x08\x00\x00h\xc8' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('05bf0d08')
            ts = 1970-01-01 07:27:04
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'yhVaUqdSegHIqEeG' (total 16)
DEBUG:miio.miioprotocol:Discovered 05bf0d08 with ts: 1970-01-01 07:27:04, token: b'79685661557164536567484971456547'
DEBUG:miio.miioprotocol:192.168.8.1:54321 >>: {'id': 209, 'method': 'miIO.ota', 'params': {'mode': 'normal', 'install': '1', 'app_url': 'http://192.168.8.61:56030/v11_002034.pkg', 'file_md5': 'c1312366b2b24e7f65ff698208aded8e', 'proc': 'dnld install'}}
DEBUG:miio.protocol:Unable to parse json '': Expecting value: line 1 column 1 (char 0)
DEBUG:miio.click_common:Exception: Unable to parse message payload
Traceback (most recent call last):
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/protocol.py", line 198, in _decode
    return json.loads(decoded)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/integrations/vacuum/roborock/vacuum_cli.py", line 654, in update_firmware
    update_res = vac.update(url, md5)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/device.py", line 194, in update
    return self.send("miIO.ota", payload)[0] == "ok"
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/device.py", line 103, in send
    return self._protocol.send(
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/miioprotocol.py", line 194, in send
    m = Message.parse(data, token=self.token)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 2653, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 4295, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 4598, in _parse
    obj = self.subcon._parsereport(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/construct/core.py", line 704, in _parse
    return self._decode(obj, context, path)
  File "/Users/mustermann/Documents/valetudo/venv/lib/python3.9/site-packages/miio/protocol.py", line 204, in _decode
    raise PayloadDecodeException(
miio.exceptions.PayloadDecodeException: Unable to parse message payload
Error: Unable to parse message payload
ERROR:miio.updater:No request was made..
```

**Comment by rytilahti** [comment]
This is likely a duplicate of #1103.

**Comment by tegger2000** [comment]
yes, this is the same error. I didn't found the other one, sorry

**Comment by satheshshiva** [comment]
Latest version does not allow to upgrade firmware. Factory reset to flash the old firmware from the recovery partition that was shipped with the device and try flashing again.
