### ISSUE TITLE
installiation problems

### ISSUE THREAD

**Issue by g3d12** [rytilahti/python-miio#130]
Hi installation proccess and installed all required componets but running from the line: mirobo --help I get on Rpi3:
```
  File "/usr/local/bin/mirobo", line 7, in <module>
    from miio.vacuum_cli import cli
  File "/usr/local/lib/python3.4/dist-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "/usr/local/lib/python3.4/dist-packages/miio/protocol.py", line 30, in <module>
    from cryptography.hazmat.primitives import padding
  File "/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: No module named '_cffi_backend'
```
and on other RPI model A:
```
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 7, in <module>
    from miio.vacuum_cli import cli
  File "/usr/local/lib/python3.4/dist-packages/miio/__init__.py", line 2, in <mo                                                                                                                                                             dule>
    from miio.protocol import Message, Utils
  File "/usr/local/lib/python3.4/dist-packages/miio/protocol.py", line 18, in <m                                                                                                                                                             odule>
    from typing import Any, Dict, Tuple
ImportError: No module named 'typing'

```
Please help me launching it on one of those Rpi's

**Comment by rytilahti** [comment]
On Rpi3 I think you need to install `python3-cffi-backend` if not already installed. For that second error it is necessary to install `typing` with `pip`.

**Comment by rytilahti** [comment]
Ok, @g3d12 can you confirm and close the issue if it's solved with that?

The second error is due to missing typing module (as it is in the standard library only starting from 3.5), although it should be installed automatically as a dependency.

**Comment by g3d12** [comment]
Thanks, given answers let me install and use python-miio. I had to install some of the modules manually but its OK. Apart from this  I'm really missing json to operate with different programs and scripts :)

**Comment by rytilahti** [comment]
Mind noting down which modules were necessary so that we can update the documentation?

The JSON support is tracked in #98, although depending on your use-case it may be easier just to create a separate script using this library which outputs the wanted information in JSON.

**Comment by Tontze** [comment]
I just updated my  python-miio using "pip install --upgrade python-miio" And now im getting : 

Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 5, in <module>
    from miio.vacuum_cli import cli
ModuleNotFoundError: No module named 'miio.vacuum_cli'
