### ISSUE TITLE
dreame.vacuum.mc1808

### ISSUE THREAD

**Issue by ganjakyp-hub** [rytilahti/python-miio#1333]
Unfortunately not working :(

Model: dreame.vacuum.mc1808
Hardware version: Linux
Firmware version: 4.3.3_1122

**Comment by derherrgraf** [comment]
For me it is working e.g. `miiocli dreamevacuummiot --ip <IP> --token <TOKEN> status`

**Comment by DeutscheGabanna** [comment]
`miiocli dreamevacuum --ip ... --token ... status`

```
Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\Scripts\miiocli.exe\__main__.py", line 7, in <module>
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\cli.py", line 66, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\click_common.py", line 305, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\click_common.py", line 270, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\click_common.py", line 217, in call
    return method(*args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\integrations\vacuum\dreame\dreamevacuum_miot.py", line 451, in status
    {
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python38\lib\site-packages\miio\integrations\vacuum\dreame\dreamevacuum_miot.py", line 452, in <dictcomp>
    prop["did"]: prop["value"] if prop["code"] == 0 else None
KeyError: 'value'
```

When tried `miiocli dreamevacuummiot --ip ... --token ... status`

```
Usage: miiocli [OPTIONS] COMMAND [ARGS]...
Try 'miiocli --help' for help.

Error: No such command 'dreamevacuummiot'.
```
