### ISSUE TITLE
support for xiaomi.repeater.v6?

### ISSUE THREAD

**Issue by AIMAN2410** [rytilahti/python-miio#1375]

**Comment by AIMAN2410** [comment]
`miiocli -d wifirepeater --ip 192.168.41.1 --token xxx info
INFO:miio.cli:Debug mode active
DEBUG:miio.click_common:Unknown model, trying autodetection. None None
DEBUG:miio.miioprotocol:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x1c\xdb\xb6v\x00\x00\x01d' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('1cdbb676')
            ts = 1970-01-01 00:05:56
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'dRzoYZcAtAl2I02H' (total 16)
DEBUG:miio.miioprotocol:Discovered 1cdbb676 with ts: 1970-01-01 00:05:56, token: b'xxx'
DEBUG:miio.miioprotocol:192.168.41.1:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:192.168.41.1:54321 (ts: 1970-01-01 00:05:57, id: 1) << {'id': 1, 'result': {'life': 357, 'model': 'xiaomi.repeater.v6', 'token': 'xxx', 'ipflag': 1, 'miio_ver': '0.0.8', 'uptime': 400, 'mac': '3c:cd:57:95:de:94', 'fw_ver': '', 'hw_ver': '', 'miio_client_ver': '4.2.5', 'VmPeak': 1512, 'VmSize': 1512, 'VmRSS': 704, 'MemFree': 20692, 'ap': {'ssid': '', 'bssid': '', 'rssi': '', 'freq': 0}, 'netif': {'localIp': '0.0.0.0', 'mask': '0.0.0.0', 'gw': '0.0.0.0'}, 'miio_times': [356, 0, 0, 0]}, 'exe_time': 2}
DEBUG:miio.device:Detected model xiaomi.repeater.v6
WARNING:miio.device:Found an unsupported model 'xiaomi.repeater.v6' for class 'WifiRepeater'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
Model: xiaomi.repeater.v6
Hardware version:
Firmware version:`

**Comment by rytilahti** [comment]
Are the commands working with the device, i.e., is it just the warning that should be fixed?

**Comment by AIMAN2410** [comment]
Oh sorry i forgot about that XD

`C:\Users\syami>miiocli -d wifirepeater --ip 192.168.41.1 --token 506466587a7235713552656569574570 set_configuration WiFi '' 0
INFO:miio.cli:Debug mode active
Setting accesspoint configuration
DEBUG:miio.click_common:Unknown model, trying autodetection. None None
DEBUG:miio.miioprotocol:Got a response: Container:
    data = Container:
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container:
        data = b'!1\x00 \x00\x00\x00\x00\x1c\xdb\xb6v\x00\x00\x00\xd4' (total 16)
        value = Container:
            length = 32
            unknown = 0
            device_id = unhexlify('1cdbb676')
            ts = 1970-01-01 00:03:32
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'PdfXzr5q5ReeiWEp' (total 16)
DEBUG:miio.miioprotocol:Discovered 1cdbb676 with ts: 1970-01-01 00:03:32, token: b'506466587a7235713552656569574570'
DEBUG:miio.miioprotocol:192.168.41.1:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:192.168.41.1:54321 (ts: 1970-01-01 00:03:33, id: 1) << {'id': 1, 'result': {'life': 213, 'model': 'xiaomi.repeater.v6', 'token': '506466587a7235713552656569574570', 'ipflag': 1, 'miio_ver': '0.0.8', 'uptime': 256, 'mac': '3c:cd:57:95:de:94', 'fw_ver': '', 'hw_ver': '', 'miio_client_ver': '4.2.5', 'VmPeak': 1512, 'VmSize': 1512, 'VmRSS': 700, 'MemFree': 22048, 'ap': {'ssid': '', 'bssid': '', 'rssi': '', 'freq': 0}, 'netif': {'localIp': '0.0.0.0', 'mask': '0.0.0.0', 'gw': '0.0.0.0'}, 'miio_times': [212, 0, 0, 0]}, 'exe_time': 2}
DEBUG:miio.device:Detected model xiaomi.repeater.v6
WARNING:miio.device:Found an unsupported model 'xiaomi.repeater.v6' for class 'WifiRepeater'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
DEBUG:miio.miioprotocol:192.168.41.1:54321 >>: {'id': 2, 'method': 'miIO.switch_wifi_ssid', 'params': [{'ssid': 'WiFi', 'pwd': "''", 'hidden': 0, 'wifi_explorer': 0}]}
DEBUG:miio.miioprotocol:192.168.41.1:54321 (ts: 1970-01-01 00:03:37, id: 2) << {'id': 2, 'error': {'code': -9999, 'message': 'user ack timeout'}, 'exe_time': 4070}
DEBUG:miio.click_common:Exception: {'code': -9999, 'message': 'user ack timeout'}
Traceback (most recent call last):
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\click_common.py", line 300, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\click_common.py", line 265, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\click_common.py", line 212, in call
    return method(*args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\click_common.py", line 179, in _wrap
    return func(self, *args, **kwargs)
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\wifirepeater.py", line 119, in set_configuration
    return self.send(
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\device.py", line 106, in send
    return self._protocol.send(
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "C:\Users\syami\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\miio\miioprotocol.py", line 274, in _handle_error
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -9999, 'message': 'user ack timeout'}
Error: {'code': -9999, 'message': 'user ack timeout'}`
