### ISSUE TITLE
Can't connect to S7 MaxV using miiocli

### ISSUE THREAD

**Issue by davidcoulson** [rytilahti/python-miio#1393]
**Describe the bug**
When issuing any command via miiocli to my S7 MaxV I get a "Error: Unable to discover the device 10.2.4.69" message. I can confirm I can ping it. S6 MaxV works fine.

Via tcpdump I can see UDP traffic heading to the vacuum, but no response.

**Version information (please complete the following information):**
 - OS: Ubuntu 21.10.
 - python-miio: miiocli, version 0.5.11

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: S7 MaxV
  - Hardware version: No idea
  - Firmware version: 4.1.5_3806

**To Reproduce**
 miiocli roborockvacuum --ip 10.2.4.69 --token  XXXXX info1.

**Expected behavior**
Expect output similar to S6 MaxV

**Console output**
$ miiocli -d roborockvacuum --ip 10.2.4.69 --token  XXXXXX info
INFO:miio.cli:Debug mode active
DEBUG:miio.integrations.vacuum.roborock.vacuum:Read stored sequence ids: {'seq': 18, 'manual_seq': 0}
DEBUG:miio.click_common:Unknown model, trying autodetection. None None
DEBUG:miio.miioprotocol:Unable to discover a device at address 10.2.4.69
DEBUG:miio.click_common:Exception: Unable to discover the device 10.2.4.69
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.9/site-packages/miio/click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.9/site-packages/miio/click_common.py", line 300, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.9/site-packages/miio/click_common.py", line 265, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/home/david/.local/lib/python3.9/site-packages/miio/click_common.py", line 212, in call
    return method(*args, **kwargs)
  File "/home/david/.local/lib/python3.9/site-packages/miio/click_common.py", line 178, in _wrap
    self._fetch_info()
  File "/home/david/.local/lib/python3.9/site-packages/miio/integrations/vacuum/roborock/vacuum.py", line 229, in _fetch_info
    info = super()._fetch_info()
  File "/home/david/.local/lib/python3.9/site-packages/miio/device.py", line 152, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "/home/david/.local/lib/python3.9/site-packages/miio/device.py", line 106, in send
    return self._protocol.send(
  File "/home/david/.local/lib/python3.9/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/home/david/.local/lib/python3.9/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.2.4.69
Error: Unable to discover the device 10.2.4.69

**Comment by rytilahti** [comment]
[S7 has been reported not to allow connections across subnets](https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets), so could this be the cause for your problem?

**Comment by davidcoulson** [comment]
Yep that is exactly it. I setup a NAT on my fw between the subnets so the S7 maxv sees the traffic from its local subnet. Seems to have fixed the issue. Thanks!
