### ISSUE TITLE
Traceback during mirobo -discover

### ISSUE THREAD

**Issue by Patr-ick** [rytilahti/python-miio#1431]
Running mirobo on M1 Macbook pro brings up this error:

xxxxxxx@MacBook-Pro-2 ~ % mirobo discover --handshake=true                   
Traceback (most recent call last):
  File "/Users/xxxxxxx/Library/Python/3.8/bin/mirobo", line 5, in <module>
    from mirobo.vacuum_cli import cli
  File "/Users/xxxxxxx/Library/Python/3.8/lib/python/site-packages/mirobo/__init__.py", line 2, in <module>
    from mirobo.protocol import Message, Utils
  File "/Users/xxxxxxx/Library/Python/3.8/lib/python/site-packages/mirobo/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "/Users/xxxxxxx/Library/Python/3.8/lib/python/site-packages/construct/core.py", line 2721, in __init__
    super().__init__(subcon)
  File "/Users/xxxxxxx/Library/Python/3.8/lib/python/site-packages/construct/core.py", line 676, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

**Comment by rytilahti** [comment]
You are running very, very old version of python-miio (or even python-mirobo?!), as mirobo package has not existed in this code base for years.

**Comment by Patr-ick** [comment]
how to update? i've installed via `pip3 install python-miio`

**Comment by rytilahti** [comment]
That should work... What does `pip show python-miio` show as the version? What's the version of `construct` (`pip show construct`)?

**Comment by Patr-ick** [comment]
pip show python-miio
```
Name: python-miio
Version: 0.5.11
Summary: Python library for interfacing with Xiaomi smart appliances
Home-page: https://github.com/rytilahti/python-miio
Author: Teemu R
Author-email: tpr@iki.fi
License: GPL-3.0-only
Location: /Users/patrickbilan/flasher/venv/lib/python3.8/site-packages
Requires: android_backup, appdirs, attrs, click, construct, croniter, cryptography, defusedxml, netifaces, pytz, PyYAML, tqdm, zeroconf
Required-by: 
```
pip show construct
```
Name: construct
Version: 2.10.68
Summary: A powerful declarative symmetric parser/builder for binary data
Home-page: http://construct.readthedocs.org
Author: Arkadiusz Bulski, Tomer Filiba, Corbin Simpson
Author-email: arek.bulski@gmail.com, tomerfiliba@gmail.com, MostAwesomeDude@gmail.com
License: MIT
Location: /Users/patrickbilan/flasher/venv/lib/python3.8/site-packages
Requires: 
Required-by: python-miio
```

**Comment by Patr-ick** [comment]
Yup, I've tried first by installing pip etc. in the users directory `/Users/xxxxxxx/Library/Python/` but received an warning, that `/Users/xxxxxxx/Library/Python/` is not on PATH. So did another try inside a virtual env.

```
(venv) xxxxx@MacBook-Pro flasher % mirobo discover
Traceback (most recent call last):
  File "/Users/xxxxx/Library/Python/3.8/bin/mirobo", line 5, in <module>
    from mirobo.vacuum_cli import cli
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/mirobo/__init__.py", line 2, in <module>
    from mirobo.protocol import Message, Utils
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/mirobo/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/construct/core.py", line 2721, in __init__
    super().__init__(subcon)
  File "/Users/xxxxx/Library/Python/3.8/lib/python/site-packages/construct/core.py", line 676, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
```
Seems like even in the virtual env mirobo tries to get .py files from the `/Users/xxxxx/Library/Python/3.8/lib/python` directory. anyway to avoid that and force the site-packages taking from the virtual env directory?

**Comment by rytilahti** [comment]
Alas, it really depends on your python environment. Maybe just remove the non-virtualenv installation using `pip uninstall`? Also, make sure that no `python-mirobo` is installed, that mirobo package (`site-packages/mirobo/..`) has not been shipped for years iirc.

**Comment by PaXLiCh** [comment]
Any progress on fixing the bug?
