### ISSUE TITLE
Vaccum Timer / Timezone issue

### ISSUE THREAD

**Issue by battosai30** [rytilahti/python-miio#149]
Hi,

I noticed errors trying to play with timers on mirobo.
First this is what I get with mirobo timezone : 

```
ERROR:miio.device:Unable to discover a device at address 192.168.1.7
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/miio/vacuum_cli.py", line 445, in timezone
    click.echo("Timezone: %s" % vac.timezone())
  File "/usr/local/lib/python3.5/dist-packages/miio/vacuum.py", line 225, in timezone
    return self.send("get_timezone")[0]
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 201, in send
    self.do_discover()
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 141, in do_discover
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.device.DeviceException: Unable to discover the device 192.168.1.7

```

Secondly, this is what I get on mirobo timer ;

`Timezone: Europe/Paris`

Yes, I get the timezone on timer command.

Regards

**Comment by rytilahti** [comment]
The first error is very generic and means just that the device did not answer to the discovery request. Which version of mirobo are you running? (`mirobo --version`)

Accessing `timer` will also print out the timezone, so maybe you do not have saved any timers? Here's the output of both commands with mirobo 0.3.2:
```
(venv) $ mirobo timezone
Timezone: Europe/Berlin

(venv) hass@rasputin:~ $ mirobo timer
Timezone: Europe/Berlin

Timer #0, id 1488667726378 (ts: 2017-03-04 23:48:46.378000)
  48 18 * * 1,2,3,4,5
  At 18:48 every Monday, Tuesday, Wednesday, Thursday and Friday
Timer #1, id 1488667715725 (ts: 2017-03-04 23:48:35.725000)
  48 17 * * 0,1,2,3,4,5,6
  At 17:48 every Sunday, Monday, Tuesday, Wednesday, Thursday, Friday and Saturday
Timer #2, id 1505506963292 (ts: 2017-09-15 22:22:43.292000)
  * * * * *
  Every minute of every day
```

**Comment by battosai30** [comment]
Oops you were right : timezone error seems to be a colision with another application I made on nodered, and I add no timer programmed for  now so it was normal that nothing more than timezone was displayed.

So thanks again and sorry for the waste of time
