### ISSUE TITLE
Error with info command

### ISSUE THREAD

**Issue by reinerh** [rytilahti/python-miio#156]
When running `mirobo info` I get the following error:
```
INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Read stored sequence ids: {'seq': 645, 'manual_seq': 0}
DEBUG:miio.vacuum_cli:Connecting to 10.0.11.100 with token xxxxxxxxxxxxx
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container: 
    data = Container: 
        data =  (total 0)
        value =  (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = !1\x00 \x00\x00\x00\x00\x04m\xf8\xe2\x00\x00\x1e\xf1 (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = 00aabbcc (total 8)
            ts = 1970-01-01 02:12:01
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = \xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff (total 16)
DEBUG:miio.device:Discovered b'00aabbcc' with ts: 1970-01-01 02:12:01, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.device:10.0.11.100:54321 >>: {'id': 646, 'method': 'miIO.info', 'params': []}
ERROR:miio.protocol:unable to parse json '': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/mirobo", line 11, in <module>
    load_entry_point('python-miio==0.3.3', 'console_scripts', 'mirobo')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/miio/vacuum_cli.py", line 391, in info
    res = vac.info()
  File "/usr/lib/python3/dist-packages/miio/device.py", line 271, in info
    return DeviceInfo(self.send("miIO.info", []))
  File "/usr/lib/python3/dist-packages/miio/device.py", line 239, in send
    self.__id = m.data.value["id"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rytilahti** [comment]
If it is a vacuum without cloud connectivity, this is expected. However, the error message could be better in that case and it should be fixed.

**Comment by reinerh** [comment]
Yes, it's a vacuum with no internet connectivity.

**Comment by rytilahti** [comment]
Ok, there's really nothing we can do for that, expect handle the error better (and inform the user that it's not going to work in those cases. Let's keep this open until that's done, thanks!
