### ISSUE TITLE
No response from the device: gateway

### ISSUE THREAD

**Issue by HeisenbergK** [rytilahti/python-miio#1605]
**Describe the bug**
I used this code:
```
from miio import Gateway

gateway_ip = ""
token = ""

if __name__ == "__main__":
    gateway = Gateway(gateway_ip, token)
    gateway.discover_devices()
    print(gateway.devices)
    print(gateway.devices[""].get_property("temperature"))

```
(ip, token and device name redacted for safety)

It did work and I did get the temperature. But all subsequent re-runs give me `miio.exceptions.DeviceException: No response from the device`

**Version information (please complete the following information):**
 - OS: MacOS-12.6.1
 - python-miio: 0.5.12
 - Python: 3.9.13

**Device information:**
If the issue is specific to a device (I found the data in the mi app, the command you provided is not working):
  - Model: lumi.gateway.mgl03
  - Hardware version: v1.4.6_0043
  - Firmware version: v1.4.6_0043

**To Reproduce**
1. Run above code

**Expected behavior**
Get the subdevices of the gateway

**Console output**
```
Got error when receiving: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/johnkypriotakis/testmi/testmi.py", line 8, in <module>
    gateway.discover_devices()
  File "/usr/local/lib/python3.9/site-packages/miio/click_common.py", line 183, in _wrap
    self._fetch_info()
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 241, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
```

**Comment by HeisenbergK** [comment]
I am getting no responses. I will close this as inactive now.
