### ISSUE TITLE
Error when using miiocli genericmiot for device zhimi.heater.mc2

### ISSUE THREAD

**Issue by pplucky** [rytilahti/python-miio#1619]
**Describe the bug**
Error when running miiocli genericmiot for device `zhimi.heater.mc2`

**Version information (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye) (5.15.61-v7l+) 
 - python-miio: Latest master installed and ran via poetry

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: zhimi.heater.mc2
  - Hardware version: esp32
  - Firmware version: 2.2.1

**To Reproduce**
1. Run miiocli genericmiot --ip <IP> --token <TOKEN> status

**Expected behavior**
Device status information provided without errors

**Console output**
```
DEBUG:miio.miioprotocol:172.16.23.97:54321 >>: {'id': 2,
 'method': 'get_properties',
 'params': [{'did': 'heater:on', 'piid': 1, 'siid': 2},
            {'did': 'heater:fault', 'piid': 2, 'siid': 2},
            {'did': 'heater:target-temperature', 'piid': 5, 'siid': 2},
            {'did': 'countdown:countdown-time', 'piid': 1, 'siid': 3},
            {'did': 'environment:temperature', 'piid': 7, 'siid': 4},
            {'did': 'physical-controls-locked:physical-controls-locked',
             'piid': 1,
             'siid': 5},
            {'did': 'alarm:alarm', 'piid': 1, 'siid': 6},
            {'did': 'indicator-light:brightness', 'piid': 3, 'siid': 7},
            {'did': 'private-service:hw-enable', 'piid': 8, 'siid': 8},
            {'did': 'private-service:use-time', 'piid': 9, 'siid': 8}]}
DEBUG:miio.miioprotocol:172.16.23.97:54321 (ts: 1970-01-01 02:09:43, id: 2) << {'exe_time': 630,
 'id': 2,
 'result': [{'code': 0,
             'did': 'heater:on',
             'piid': 1,
             'siid': 2,
             'value': True},
            {'code': 0,
             'did': 'heater:fault',
             'piid': 2,
             'siid': 2,
             'value': 0},
            {'code': 0,
             'did': 'heater:target-temperature',
             'piid': 5,
             'siid': 2,
             'value': 20},
            {'code': 0,
             'did': 'countdown:countdown-time',
             'piid': 1,
             'siid': 3,
             'value': 0},
            {'code': 0,
             'did': 'environment:temperature',
             'piid': 7,
             'siid': 4,
             'value': 17.1},
            {'code': 0,
             'did': '335255013',
             'piid': 1,
             'siid': 5,
             'value': False},
            {'code': 0,
             'did': 'alarm:alarm',
             'piid': 1,
             'siid': 6,
             'value': False},
            {'code': 0,
             'did': 'indicator-light:brightness',
             'piid': 3,
             'siid': 7,
             'value': 1},
            {'code': 0,
             'did': 'private-service:hw-enable',
             'piid': 8,
             'siid': 8,
             'value': False},
            {'code': 0,
             'did': 'private-service:use-time',
             'piid': 9,
             'siid': 8,
             'value': 65535}]}
DEBUG:miio.miioprotocol:172.16.23.97:54321 >>: {'id': 3,
 'method': 'get_properties',
 'params': [{'did': 'private-service:country-code', 'piid': 10, 'siid': 8}]}
DEBUG:miio.miioprotocol:172.16.23.97:54321 (ts: 1970-01-01 02:09:43, id: 3) << {'exe_time': 630,
 'id': 3,
 'result': [{'code': 0,
             'did': 'private-service:country-code',
             'piid': 10,
             'siid': 8,
             'value': 44}]}
ERROR:miio.click_common:Exception: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/home/pi/python-miio/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.cache/pypoetry/virtualenvs/python-miio-RFxuN8Yf-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/.cache/pypoetry/virtualenvs/python-miio-RFxuN8Yf-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.cache/pypoetry/virtualenvs/python-miio-RFxuN8Yf-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.cache/pypoetry/virtualenvs/python-miio-RFxuN8Yf-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.cache/pypoetry/virtualenvs/python-miio-RFxuN8Yf-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/python-miio/miio/click_common.py", line 310, in wrap
    result_msg = result_msg_fmt(**kwargs)
  File "/home/pi/python-miio/miio/integrations/genericmiot/genericmiot.py", line 28, in pretty_status
    props = result.property_dict()
  File "/home/pi/python-miio/miio/integrations/genericmiot/genericmiot.py", line 109, in property_dict
    service, prop_name = did.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by pplucky** [comment]
Looking good now for `zhimi.heater.mc2`:
```
[S] Switch Status (heater:on): False
Device Fault (heater:fault): 0  (min: 0, max: 255, step: 1)
[S] Target Temperature (heater:target-temperature): 20 None (min: 18, max: 28, step: 1)
[S] Countdown Time (countdown:countdown-time): 0:00:00 (min: 0, max: 12, step: 1)
Temperature (environment:temperature): 19.4 None (min: -30, max: 100, step: 0)
[S] Physical Control Locked (physical-controls-locked:physical-controls-locked): False
[S] Alarm (alarm:alarm): False
[S] Brightness (indicator-light:brightness): 1 % (min: 0, max: 1, step: 1)
[S] 恒温功能使能 (private-service:hw-enable): False
用户使用时长 (private-service:use-time): 66253 None (min: 0, max: 2147483647, step: 1)
country-code (private-service:country-code): EU,欧洲 (value: 44) (from: 未知 (0), US, 美国 (1), KR,韩国 (82), EU,欧洲 (44), JP,日本 (81), RU，俄罗斯 (7), CN,中国 (86), 中国香港 (852), 中国台湾 (886), FR,法国 (33))
```
