### ISSUE TITLE
run `miiocli --version` raise error

### ISSUE THREAD

**Issue by xavierskip** [rytilahti/python-miio#1669]
**Describe the bug**
when run command `miiocli --version` you can't get the version info but raise error

**Version information (please complete the following information):**
 - OS: kali Linux on WSL 2
 - python-miio: 0.5.12 

**Device information:**
I install through `python3 -m pip install python-miio`.
```
$ which python3
/usr/bin/python3

$ python3 -V
Python 3.10.9

$ pip -V
pip 22.3.1 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

**To Reproduce**
1.`miiocli --version`

**Expected behavior**
emm, see the version number

**Console output**
```
Traceback (most recent call last):
  File "/home/skip/.local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/home/skip/.local/lib/python3.10/site-packages/miio/cli.py", line 66, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/home/skip/.local/lib/python3.10/site-packages/miio/click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "/home/skip/.local/lib/python3.10/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/skip/.local/lib/python3.10/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/skip/.local/lib/python3.10/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/skip/.local/lib/python3.10/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/skip/.local/lib/python3.10/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/skip/.local/lib/python3.10/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/skip/.local/lib/python3.10/site-packages/click/decorators.py", line 441, in callback
    raise RuntimeError(
RuntimeError: 'miio' is not installed. Try passing 'package_name' instead.
```

and i can use `miiocli genericmiot` command, it shows `Error: No such command 'genericmiot'.` 

so i consider it may be pip version is out of time, the github  Releases may be ok.

but need some fix the pip version.

**Comment by rytilahti** [comment]
I'm not sure why the `--version` is not working, potentially related to click itself. What does `pip show click` show for version? You can also use the same command to check the version of python-miio.

The `genericmiot` is only available in the current git master branch and it will take some time until a new release gets done. In the meantime, if you want to give it a try, you can always install directly from git.

**Comment by xavierskip** [comment]
```
$ pip show click
Name: click
Version: 8.1.3
....

```

**Comment by rytilahti** [comment]
Ah, it's indeed a bug. No idea when it stopped working, but the linked PR will fix it. Thanks for reporting this @xavierskip!
