### ISSUE TITLE
pydantic - extra fields not permitted (gatt-access)

### ISSUE THREAD

**Issue by skymkmk** [rytilahti/python-miio#1721]
This issue is translated by DeepL from Chinese.

**Describe the bug**

When I try to control [cuco.plug.v3](https://home.miot-spec.com/spec/cuco.plug.v3) using this project, the following error is thrown:

```
pydantic.error_wrappers.ValidationError: 5 validation errors for DeviceModel
services -> 3 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 3 -> properties -> 1 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 12 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 12 -> properties -> 1 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 13 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
```

I've never used pydantic, so I googled and found that this thing seems to include the ability to validate schema, so I tried removing all the gatt-access fields from the cache and after that it was back to normal and I could control my device normally.

**Version information (please complete the following information):**

 - OS: Windows 11 22H2 and Rocky Linux 8.7
 - python-miio: 0.6.0.dev0

**Device information:**

  - Model: cuco.plug.v3
  - Hardware version: ESP32C3
  - Firmware version: 1.0.6

**To Reproduce**

All commands and api that use genericmiot.

**Expected behavior**

No exception are thrown.

**Console output**

```
ERROR:miio.click_common:Exception: 5 validation errors for DeviceModel
services -> 3 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 3 -> properties -> 1 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 12 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 12 -> properties -> 1 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 13 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\click_common.py", line 314, in wrap
    result_msg = result_msg_fmt(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\device.py", line 45, in _info_output
    dev = DeviceFactory.create(result.ip_address, result.token, force_generic_miot=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\devicefactory.py", line 101, in create
    dev.info()
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\click_common.py", line 184, in _wrap
    self._fetch_info()
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\integrations\genericmiot\genericmiot.py", line 344, in _fetch_info
    self.initialize_model()
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\integrations\genericmiot\genericmiot.py", line 206, in initialize_model
    self._miot_model = miotcloud.get_device_model(self.model)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\miot_cloud.py", line 66, in get_device_model
    return DeviceModel.parse_obj(spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "D:\projects\remote-boot\.venv\Lib\site-packages\miio\miot_models.py", line 436, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for DeviceModel
services -> 3 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 3 -> properties -> 1 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 12 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 12 -> properties -> 1 -> gatt-access
  extra fields not permitted (type=value_error.extra)
services -> 13 -> properties -> 0 -> gatt-access
  extra fields not permitted (type=value_error.extra)
```

**Comment by rytilahti** [comment]
Thanks for testing and reporting, @skymkmk, it's great to receive reports like this! The pydantic constraints are set strict for development purposes to avoid hiding any potentially useful information. 

Looks like this device does not have any content behind that key (gatt is something that's used for bluetooth communications), so I left its interpretation open in the linked PR.
