### ISSUE TITLE
Miiocli Windows, System cannot find specified path

### ISSUE THREAD

**Issue by AquaCobell** [rytilahti/python-miio#1785]
**Describe the bug**
After following the documentation and installing miiocli with pip install python-miio I get the following error:

miiocli device --ip 192.168.188.63 --token a4d08xxxxxxxxdaxxxxxxxxx1e03c9 info
ERROR:miio.click_common:Exception: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Nico\\AppData\\Local\\python-miio\\python-miio\\Cache'
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Nico\\AppData\\Local\\python-miio\\python-miio\\Cache'

My python executable and scripts folder is added to the system variable.
there is no folder under C:\\Users\\Nico\\AppData\\Local\\python-miio\\python-miio\\Cache

**Version information (please complete the following information):**
 - OS: Windows 10 
 - python-miio: miiocli, version 0.6.0.dev0

**To Reproduce**
1. Install miiocli
2. 2. use the miiocli device --ip 192.168.188.63 --token a4d08xxxxxxxxdaxxxxxxxxx1e03c9 info 

**Console output**
ERROR:miio.click_common:Exception: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Nico\\AppData\\Local\\python-miio\\python-miio\\Cache'
Traceback (most recent call last):
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\click_common.py", line 313, in wrap
    result_msg = result_msg_fmt(**kwargs)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\device.py", line 46, in _info_output
    dev = DeviceFactory.create(result.ip_address, result.token, force_generic_miot=True)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\devicefactory.py", line 101, in create
    dev.info()
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\click_common.py", line 184, in _wrap
    self._fetch_info()
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\integrations\genericmiot\genericmiot.py", line 199, in _fetch_info
    self.initialize_model()
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\integrations\genericmiot\genericmiot.py", line 65, in initialize_model
    self._miot_model = miotcloud.get_device_model(self.model)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\miot_cloud.py", line 68, in get_device_model
    return DeviceModel.parse_obj(self.get_model_schema(model))
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\miot_cloud.py", line 72, in get_model_schema
    specs = self.get_release_list()
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\miot_cloud.py", line 119, in get_release_list
    self._write_to_cache(cache_file, specs)
  File "C:\Users\Nico\AppData\Roaming\Python\Python310\site-packages\miio\miot_cloud.py", line 87, in _write_to_cache
    file.parent.mkdir(exist_ok=True)
  File "C:\Program Files\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Nico\\AppData\\Local\\python-miio\\python-miio\\Cache'

**Comment by rytilahti** [comment]
Thanks for the report! You could create that directory structure manually to be able to use it until this gets fixed.
