### ISSUE TITLE
Support Roborock Q Revo(roborock.vacuum.a75)

### ISSUE THREAD

**Issue by bchen290** [rytilahti/python-miio#1796]
If you are receiving a warning indicating an unsupported model (`Found an unsupported model '<model>' for class '<class>'.`),
this means that the implementation does not list your model as supported.

If it is working fine for you nevertheless, feel free to open an issue or create a PR to add the model to the `_supported_models` ([example](https://github.com/rytilahti/python-miio/blob/72cd423433ad71918b5a8e55833a5b2eda9877a5/miio/integrations/vacuum/roborock/vacuum.py#L125-L153)) for that class.

Before submitting, use the search to see if there is an existing issue for the device model, thanks!

**Device information:**

  - Name(s) of the device: roborock.vacuum.a75
  - Link: https://us.roborock.com/products/roborock-q-revo

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: roborock.vacuum.a75
  - Hardware version:
  - Firmware version:

**Comment by DennYoDeluxe** [comment]
same Issue:
Found an unsupported model 'roborock.vacuum.a75' for class 'RoborockVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/

Running the very new Roborock Q Revo

**Comment by mindgam3s** [comment]
+1

**Comment by Darkside138** [comment]
Bump, have this vacuum and it's working great with the integration

**Comment by littlesteve01** [comment]
Hallo, ist this Model working/supported?

**Comment by rytilahti** [comment]
So what exactly is not working? Most (if not all) roborock vacuums should be supported but there may be some missing features depending on the model.

**Comment by lmuser22** [comment]
getting this Report für my A75


Output:


WARNING:miio.device:Found an unsupported model 'roborock.vacuum.a75' for class 'ViomiVacuum'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
WARNING:miio.integrations.vacuum.viomi.viomivacuum:Unknown vacuum state: None
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.9/dist-packages/miio/cli.py", line 66, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.9/dist-packages/miio/click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/miio/click_common.py", line 310, in wrap
    result_msg = result_msg_fmt.format(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/miio/integrations/vacuum/viomi/viomivacuum.py", line 325, in bin_type
    return ViomiBinType(self.data["box_type"])
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 677, in __new__
    raise ve_exc
ValueError: None is not a valid ViomiBinType

**Comment by rytilahti** [comment]
@lmuser22 you need to use `miiocli roborockvacuum` to control roborocks, you are somehow trying to control yours as a viomi vacuum which isn't obviously working.

**Comment by chen-tianjian** [comment]
Quick question: is Roborock Q Revo MaxV supported?
