### ISSUE TITLE
miiocli --version error

### ISSUE THREAD

**Issue by Flavien06** [rytilahti/python-miio#1811]
**Describe the bug**
I have error when i use miiocli --version

**Version information (please complete the following information):**
 - OS: Raspbery Pi : 6.1.23-v7+
 - python-miio: 
Name: python-miio
Version: 0.5.12
Summary: Python library for interfacing with Xiaomi smart appliances
Home-page: https://github.com/rytilahti/python-miio
Author: Teemu R
Author-email: tpr@iki.fi
License: GPL-3.0-only
Location: /home/pi/.local/lib/python3.9/site-packages
Requires: android_backup, appdirs, attrs, click, construct, croniter, cryptography, defusedxml, micloud, netifaces, pytz, PyYAML, tqdm, zeroconf
Required-by:

 - pip 23.2 from /home/pi/.local/lib/python3.9/site-packages/pip (python 3.9)

**Console output**
miiocli --version
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/home/pi/.local/lib/python3.9/site-packages/miio/cli.py", line 66, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/home/pi/.local/lib/python3.9/site-packages/miio/click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/pi/.local/lib/python3.9/site-packages/click/decorators.py", line 441, in callback
    raise RuntimeError(
RuntimeError: 'miio' is not installed. Try passing 'package_name' instead.

**Comment by wiselike** [comment]
fixed in https://github.com/rytilahti/python-miio/issues/1669
