### ISSUE TITLE
INFO cmd return a FileNotFoundError

### ISSUE THREAD

**Issue by tomitomas** [rytilahti/python-miio#1818]
**Describe the bug**
the `info` command does NOT give a valid return for an unsupported device
while in the documentation we can read : 
```
First, you can use info to get some generic information from any (**even yet unsupported**) device
```

**Version information (please complete the following information):**
 - OS: debian 10
 - python-miio:  0.6.0.dev0

**Device information:**
```
debian:~$ miiocli device --ip 192.168.0.3 --token xxx  info
ERROR:miio.click_common:Exception: Cache file /root/.cache/python-miio/roborock.vacuum.a51.json not found or it is stale
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 313, in wrap
    result_msg = result_msg_fmt(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 46, in _info_output
    dev = DeviceFactory.create(result.ip_address, result.token, force_generic_miot=True)
  File "/usr/local/lib/python3.8/site-packages/miio/devicefactory.py", line 101, in create
    dev.info()
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 184, in _wrap
    self._fetch_info()
  File "/usr/local/lib/python3.8/site-packages/miio/integrations/genericmiot/genericmiot.py", line 199, in _fetch_info
    self.initialize_model()
  File "/usr/local/lib/python3.8/site-packages/miio/integrations/genericmiot/genericmiot.py", line 65, in initialize_model
    self._miot_model = miotcloud.get_device_model(self.model)
  File "/usr/local/lib/python3.8/site-packages/miio/miot_cloud.py", line 83, in get_device_model
    spec = self._file_from_cache(file)
  File "/usr/local/lib/python3.8/site-packages/miio/miot_cloud.py", line 125, in _file_from_cache
    raise FileNotFoundError("Cache file %s not found or it is stale" % file)
FileNotFoundError: Cache file /root/.cache/python-miio/roborock.vacuum.a51.json not found or it is stale
```

**To Reproduce**
run the info cmd

**Expected behavior**
as described in the documentation, a return like : 
```
Model: XXX
Hardware version: MW300
Firmware version: 1.2.4_16
Supported using: RoborockVacuum
Command: miiocli roborockvacuum --ip 127.0.0.1 --token 00000000000000000000000000000000
Supported by genericmiot: False
```

or at least , it would be great to have : 
```
Supported by genericmiot: False
```

**Comment by rytilahti** [comment]
That's a bug in current master, thanks for reporting! You can either use the pypi version, or modify this part:
```
  File "/usr/local/lib/python3.8/site-packages/miio/device.py", line 46, in _info_output
    dev = DeviceFactory.create(result.ip_address, result.token, force_generic_miot=True)
```
by changing the `force_generic_miot` to `False`.

**Comment by tomitomas** [comment]
thanks for the reply 

with the change applied, I went from 
```
FileNotFoundError: Cache file /root/.cache/python-miio/roborock.vacuum.a51.json not found or it is stale
```

to 
```

debian:~$ miiocli device --ip 192.168.0.3 --token xxxx info
Model: roborock.vacuum.a51
Hardware version: Linux
Firmware version: 4.3.5_1476
Supported using: RoborockVacuum
Command: miiocli roborockvacuum --ip 192.168.0.3 --token 527341523767327a454b44784f555874
Supported by genericmiot: True
```

so it supports genericmiot, but the command which should be used says `roborockvacuum`  ? 

I was thinking about getting as last line 
`Supported by genericmiot: False`, shouldnt it ??

**Comment by tomitomas** [comment]
the genericmiot cmd returns the following error, that's why I think genericmiot  does not support the model yet, and should return a "False" with the previous `info` cmd :  

```
debian:~$ sudo  miiocli genericmiot --ip 192.168.0.3 --token xxxx  status                                                   
Running command status
ERROR:miio.click_common:Exception: Cache file /root/.cache/python-miio/roborock.vacuum.a51.json not found or it is stale
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 305, in wrap
    result = kwargs["result"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 270, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 218, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/miio/click_common.py", line 184, in _wrap
    self._fetch_info()
  File "/usr/local/lib/python3.8/site-packages/miio/integrations/genericmiot/genericmiot.py", line 199, in _fetch_info
    self.initialize_model()
  File "/usr/local/lib/python3.8/site-packages/miio/integrations/genericmiot/genericmiot.py", line 65, in initialize_model
    self._miot_model = miotcloud.get_device_model(self.model)
  File "/usr/local/lib/python3.8/site-packages/miio/miot_cloud.py", line 83, in get_device_model
    spec = self._file_from_cache(file)
  File "/usr/local/lib/python3.8/site-packages/miio/miot_cloud.py", line 125, in _file_from_cache
    raise FileNotFoundError("Cache file %s not found or it is stale" % file)
FileNotFoundError: Cache file /root/.cache/python-miio/roborock.vacuum.a51.json not found or it is stale 
```

**Comment by rytilahti** [comment]
It's a bug that needs to be fixed. But you can simply use the roborockvacuum integration instead for now, it is also more feature complete (to my knowledge) than the generic interface offered by miot.

**Comment by tomitomas** [comment]
Using roborockvacuum is what I do currently :)
But I'll try to integrate it in other install without knowing what device is used.

So that `info` cmd (if working) would be very usefull to know if the process should use genericmiot or something else :)


May I consider that if the `info` cmd returns an error, then the equipent might strongly not be integrated into genericmiot !?

**Comment by rytilahti** [comment]
I don't think that's a good idea. Most of the modern devices (i.e., released since 2019 or so) should be compatible with genericmiot. Feel free to try the linked PR, it seems to be working at least using the simulator:
```
❯ miiocli -d devtools miot-simulator --model roborock.vacuum.a51 
DEBUG    Cache hit, returning contents of /home/tpr/.cache/python-miio/model-to-urn.json                                                                                       miot_cloud.py:130
DEBUG    Using model='roborock.vacuum.a51' status=None type='urn:miot-spec-v2:device:vacuum:0000A006:roborock-a51:1' version=1                                                  miot_cloud.py:57
DEBUG    Cached schema not found for roborock.vacuum.a51, going to fetch it                                                                                                    miot_cloud.py:105
DEBUG    Going to download a spec for urn:miot-spec-v2:device:vacuum:0000A006:roborock-a51:1                                                                                      miotspec.py:66
DEBUG    Starting new HTTPS connection (1): miot-spec.org:443                                                                                                             connectionpool.py:1048
DEBUG    https://miot-spec.org:443 "GET /miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:roborock-a51:1 HTTP/1.1" 200 1612                              connectionpool.py:546
DEBUG    Written 9921 bytes to /home/tpr/.cache/python-miio/roborock.vacuum.a51.json                                                                                           miot_cloud.py:116
...
```
Then on another terminal, first remove the now-cached file:
```
python-miio/miio on  fix/miotcloud_get_device_model +4 -2 [$!?] via 🐍 v3.11.3 (default) 
❯ rm /home/tpr/.cache/python-miio/roborock.vacuum.a51.json
```
And execute info + genericmiot status:
```
python-miio/miio on  fix/miotcloud_get_device_model +4 -2 [$!?] via 🐍 v3.11.3 (default) 
❯ miiocli device --ip 127.0.0.1 --token 00000000000000000000000000000000 info
Model: roborock.vacuum.a51
Hardware version: MW300
Firmware version: 1.2.4_16
Supported using: RoborockVacuum
Command: miiocli roborockvacuum --ip 127.0.0.1 --token 00000000000000000000000000000000
Supported by genericmiot: True

python-miio/miio on  fix/miotcloud_get_device_model +4 -2 [$!?] via 🐍 v3.11.3 (default) 
❯ miiocli genericmiot --ip 127.0.0.1 --token 00000000000000000000000000000000 status
Running command status
Service Robot Cleaner (vacuum)
        Status (vacuum:status, access: R): Updating (value: 14)
        Device Fault (vacuum:fault, access: R): 66 
        Mode (vacuum:mode, access: RW): Full Speed (value: 104) (<class 'int'>, choices: Silent (101), Basic (102), Strong (103), Full Speed (104), Silent (105), Custom (106))
Service Battery (battery)
        Battery Level (battery:battery-level, access: R): 98 %
Service Side Cleaning Brush (brush-cleaner)
        Brush Life Level (brush-cleaner:brush-life-level, access: R): 45 %
Service Filter (filter)
        Filter Life Level (filter:filter-life-level, access: R): 33 %

```

**Comment by tomitomas** [comment]
thanks @rytilahti
fix applied looks great, no more error
