### ISSUE TITLE
rockrobo.vacuum.v1 No response from the device

### ISSUE THREAD

**Issue by PAKalucki** [rytilahti/python-miio#1826]
**Describe the bug**

**Version information (please complete the following information):**
 - OS: Ubuntu 22.04
 - python-miio: 0.5.12

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model: Mi Robot Vacuum Cleaner  (rockrobo.vacuum.v1)
  - Hardware version: v1
  - Firmware version: 3.3.9_003158

**To Reproduce**
I'm trying to connect to device using mirobo. I'm in the same subnet as device, no VLANs, no VPNs. I tried restarting device, resetting wifi and factory reset.

**Console output**
```
miiocli cloud list
Username: xxx
Locale (cn, de, i2, ru, sg, us, all): all
== Robot vacuum (Device offline ) ==
        Model: rockrobo.vacuum.v1
        Token: xxxx48354c3935596571335875387a4c
        IP: 192.168.1.28 (mac: 78:11:DC:EE:76:35)
        DID: 82946938
        Locale: cn, de

mirobo --ip 192.168.1.28 --token xxxx48354c3935596571335875387a4c --debug

INFO:miio.integrations.vacuum.roborock.vacuum_cli:Debug mode active
DEBUG:miio.integrations.vacuum.roborock.vacuum_cli:Using config: {'seq': 0, 'manual_seq': 0}
DEBUG:miio.integrations.vacuum.roborock.vacuum_cli:Connecting to 192.168.1.28 with token xxxx48354c3935596571335875387a4c 
DEBUG:miio.click_common:Unknown model, trying autodetection. None None
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x04\xf1\xabze\x07)L' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('04f1ab7a')
            ts = 2023-09-17 16:29:00
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 04f1ab7a with ts: 2023-09-17 16:29:00, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.28:54321 >>: {'id': 1, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:Retrying with incremented id, retries left: 3
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x04\xf1\xabze\x07)Q' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('04f1ab7a')
            ts = 2023-09-17 16:29:05
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 04f1ab7a with ts: 2023-09-17 16:29:05, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.28:54321 >>: {'id': 102, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:Retrying with incremented id, retries left: 2
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x04\xf1\xabze\x07)V' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('04f1ab7a')
            ts = 2023-09-17 16:29:10
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 04f1ab7a with ts: 2023-09-17 16:29:10, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.28:54321 >>: {'id': 203, 'method': 'miIO.info', 'params': []}
DEBUG:miio.miioprotocol:Retrying with incremented id, retries left: 1
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x04\xf1\xabze\x07)[' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('04f1ab7a')
            ts = 2023-09-17 16:29:15
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 04f1ab7a with ts: 2023-09-17 16:29:15, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.28:54321 >>: {'id': 304, 'method': 'miIO.info', 'params': []}
ERROR:miio.miioprotocol:Got error when receiving: timed out
DEBUG:miio.click_common:Exception: No response from the device
Traceback (most recent call last):
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prka/.local/lib/python3.10/site-packages/miio/click_common.py", line 51, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/prka/.local/lib/python3.10/site-packages/miio/integrations/vacuum/roborock/vacuum_cli.py", line 87, in cli
    ctx.invoke(status)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/prka/.local/lib/python3.10/site-packages/miio/integrations/vacuum/roborock/vacuum_cli.py", line 122, in status
    res = vac.status()
  File "/home/prka/.local/lib/python3.10/site-packages/miio/click_common.py", line 183, in _wrap
    self._fetch_info()
  File "/home/prka/.local/lib/python3.10/site-packages/miio/integrations/vacuum/roborock/vacuum.py", line 260, in _fetch_info
    info = super()._fetch_info()
  File "/home/prka/.local/lib/python3.10/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "/home/prka/.local/lib/python3.10/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 233, in send
    return self.send(
  File "/home/prka/.local/lib/python3.10/site-packages/miio/miioprotocol.py", line 241, in send
    raise DeviceException("No response from the device") from ex
miio.exceptions.DeviceException: No response from the device
Error: No response from the device

```

**Comment by rytilahti** [comment]
That error happens when the device does not try to fetch the hosted firmware package. Is the IP address you give as a parameter the correct one for the device you run the command? You could use `tcpdump` to see if the device tries to create a TCP connection to that port at all.
