### ISSUE TITLE
is mijia.camera.v1 supported

### ISSUE THREAD

**Issue by Anuj79** [rytilahti/python-miio#1906]
- Model: mijia.camera.v1 
 
its an  xiaomi camera which is able to be discovered.. but the command dont work and tmeout 

miiocli discover 

INFO:miio.miioprotocol:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.miioprotocol:  IP 192.168.1.10 (ID: 040e5173) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.miioprotocol:Discovery done
INFO:miio.discovery:Discovering devices with mDNS for 5 seconds...
INFO:miio.discovery:Found 'mijia.camera.v1' at 192.168.1.10, performing handshake
INFO:miio.discovery:Handshake successful! devid: 68047219, ts: 2024-02-25 03:01:58+00:00

 miiocli miotdevice --ip 192.168.1.10 --token xxxxx --model mijia.camera.v1 status

Running command status
ERROR:miio.click_common:Exception: 
Traceback (most recent call last):
  File "/home/pi/python/miio/lib/python3.9/site-packages/miio/click_common.py", line 55, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/miio/click_common.py", line 306, in wrap
    result = kwargs["result"] = func(*args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/miio/click_common.py", line 271, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/miio/click_common.py", line 219, in call
    return method(*args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/miio/click_common.py", line 186, in _wrap
    return func(self, *args, **kwargs)
  File "/home/pi/python/miio/lib/python3.9/site-packages/miio/device.py", line 259, in status
    raise NotImplementedError()
NotImplementedError

miiocli --version

miiocli, version 0.6.0.dev0

do i need to download the spec file so it can be supported.. 

on the older version 0.5.12
after doing 
miiocli discover
INFO:miio.miioprotocol:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.miioprotocol:  IP 192.168.1.10 (ID: 040e5173) - token: b'ffffffffffffffffffffffffffffffff'
INFO:miio.miioprotocol:Discovery done
INFO:miio.discovery:Discovering devices with mDNS for 5 seconds...
WARNING:miio.discovery:Found unsupported device mijia-camera-v1_miio68047219._miio._udp.local. at 192.168.1.10, please report to developers

then running this code in python seems to work 

    result = m.device.Device('192.168.1.10', 'xxxxx').send('get_prop', ['light'])
    print(result)
['off']

**Comment by Anuj79** [comment]
miiocli chuangmicamera --ip 192.168.1.10 --token xxxxx  get_nas_config
Getting NAS config info
{'share': None, 'state': 0, 'error_code': 0, 'sync_interval': 600, 'video_retention_time': 0, 'last_sync_time': 0}
