### ISSUE TITLE
chuangmi.camera.026c05 unable to connect | code:  -10000 , user undefined error

### ISSUE THREAD

**Issue by 4nkitd** [rytilahti/python-miio#1988]
**Describe the bug**
unable to get device info.

**Version information (please complete the following information):**
 - OS: Linux ( ubuntu )
 - python-miio: `pip show python-miio]

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version: chuangmi.camera.026c05
  - Firmware version: 4.3.4_0443

**To Reproduce**
1. run below given code
```python
import miio;

result = miio.device.Device('192.168.x.x', '53784f4xxxxxxxxxxxxxxxxxxx').send('get_ipcprop', ['all'])

print(result)
```

**Console output**
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 270, in send
    raise DeviceError(m.data.value["error"])
miio.exceptions.DeviceError: {'code': -10000, 'message': 'user undefined error'}
Can't read output line 1 from command: 
python3 -c "import miio;result = miio.device.Device('192.168.x.x', '53784f4xxxxxxxxxxxx')
.send('get_ipcprop', ['all']);print(result['p2p_id']);print(result['avID']);print(result['avPass']);"
Error connecting to camera, make sure ip and token are correct.
Error, waiting 10 seconds and trying again.
```

**Comment by feca81** [comment]
Hi, is there any progress or workaorund about this? have the same issue
