### ISSUE TITLE
Only first request works, then "Unable to discover the device" until network adapter reset

### ISSUE THREAD

**Issue by sushi1808** [rytilahti/python-miio#1989]
**Describe the bug**
When sending a request via genericmiot to viomi.airp.v3, only the first request works (the device responds), but every subsequent attempt results in an "Unable to discover the device" error. This issue persists until I either restart my computer or reset my network adapter using Get-NetAdapter | Restart-NetAdapter.

The problem occurs on computers running Windows Server 2022 Standard (21H2) and Windows 10 Pro (22H2), both connected via Ethernet to a router running OpenWRT. However, on a laptop running Windows 11 Pro (23H2) connected to the same network wirelessly, it works as expected every time.

All three computers are running the same version of python-miio (0.6.0.dev0) and have the same version of Python installed (3.13.1). I have tried various troubleshooting steps, including disabling Windows Defender antivirus, opening ports on the Windows Firewall, disabling the firewall entirely, modifying network sharing settings, using different Ethernet adapter drivers, but none have resolved the issue.

**Version information (please complete the following information):**
 - OS: Windows Server 2022 Standard (21H2) and Windows 10 Pro (22H2)
 - python-miio: (0.6.0.dev0)

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token> info`]:
  - Model:
  - Hardware version:
  - Firmware version:

**To Reproduce**
1.

**Expected behavior**

**Console output**
PS C:\Users\Administrator> miiocli -dd genericmiot --ip 192.168.X.X --token 120d288efe8273a7e76ccXXXXXXXX set air_purifier_on_2_1 "False"
C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\miot_device.py:23: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in enum.member() if you want to preserve the old behavior
  Bool = partial(_str2bool)
Running command set
DEBUG:miio.click_common:Unknown model, trying autodetection
DEBUG:miio.miioprotocol:Unable to discover a device at address 192.168.X.X
ERROR:miio.click_common:Exception: Unable to discover the device 192.168.X.X
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\click_common.py", line 55, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\click_common.py", line 306, in wrap
    result = kwargs["result"] = func(*args, **kwargs)
                                ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\click_common.py", line 271, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\click_common.py", line 219, in call
    return method(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\click_common.py", line 185, in _wrap
    self._fetch_info()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\device.py", line 138, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
                         ~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\device.py", line 98, in send
    return self._protocol.send(
           ~~~~~~~~~~~~~~~~~~~^
        command, parameters, retry_count, extra_parameters=extra_parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\miioprotocol.py", line 168, in send
    self.send_handshake()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\miio\miioprotocol.py", line 81, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.X.X
PS C:\Users\Administrator>

**Comment by sushi1808** [comment]
UPDATE:
After two days of absolute head-banging, I turned to my friend, ChatGPT, in a last-ditch effort... and he proposed a solution:

Solutions
1. Clear Network State
After each command or discovery, explicitly close any lingering network connections or flush the ARP cache:

bash solution:
arp -d [device-ip]

In Python, you could use os.system to automate this:
import os
os.system("arp -d 192.168.1.100")  # Replace with your device's IP

I have incorporated this into my Python script so that the ARP cache is flushed after every request.

This is a good enough solution for me, and I hope it will help some other user facing the same issue.
