### ISSUE TITLE
TypeError: build() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by kofec** [rytilahti/python-miio#201]
import miio.airpurifier
MyAir = miio.airpurifier.AirPurifier(args.IPaddress, args.token)

```
Traceback (most recent call last):
  File "./MyAir.py", line 64, in <module>
    print(MyAir.status()) - 
  File "/usr/local/lib/python3.5/dist-packages/miio/airpurifier.py", line 215, in status
    properties[0:13]
  File "/usr/local/lib/python3.5/dist-packages/miio/device.py", line 216, in send
    m = Message.build(msg, ctx)
TypeError: build() takes 2 positional arguments but 3 were given
```

**Comment by syssi** [comment]
It's already fixed (master) and will be part oft the next release.

**Comment by aebgit** [comment]
inbetween you can just replace the content of your `usr/local/lib/python3.5/dist-packages/miio/device.py` with this one https://raw.githubusercontent.com/rytilahti/python-miio/17c7a26602b4d11d6a2563ba19eade4b73c7608a/miio/device.py
