### ISSUE TITLE
construct.core.StreamError: could not write bytes, expected 4, found 8

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-miio#227]
@arekbulski Do you have an idea what's missing here?

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_platform.py", line 197, in _async_add_entity
    yield from entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 325, in async_device_update
    yield from self.async_update()
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/fan/xiaomi_miio.py", line 253, in async_update
    self._air_purifier.status)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/miio/airpurifier.py", line 346, in status
    values.extend(self.send("get_prop", _props[:15]))
  File "/srv/homeassistant/lib/python3.4/site-packages/miio/device.py", line 227, in send
    m = Message.build(msg, token=self.token)
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 281, in build
    self.build_stream(obj, stream, **kw)
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 297, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 1949, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 2388, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 4181, in _build
    ret = self.subcon._build(value, stream, context, path)
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 1949, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/srv/homeassistant/lib/python3.4/site-packages/construct/core.py", line 2392, in _build
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.StreamError: could not write bytes, expected 4, found 8
    (building) -> header -> device_id
```

**Comment by arekbulski** [comment]
Its somehow related to that Hex field. Should have been fixed by #226 . Test against it.

**Comment by syssi** [comment]
It looks like unhexlify is needed here. I'm testing #226 right now. This issue is the result.

**Comment by syssi** [comment]
Do you agree with this change? https://github.com/rytilahti/python-miio/pull/228

**Comment by arekbulski** [comment]
I am not faimiliar with how you handle the parsed data, I can only tell you what constructs are valid as far as the library itself is concerned.

I already declined to provide support. Ignoring repo, wont be tracking this thread.

**Comment by syssi** [comment]
Wow. I didn't realize your decline. Sorry for the noise and the bad mood!? This wasn't my intention at any moment.
