### ISSUE TITLE
I can not start mirobo

### ISSUE THREAD

**Issue by renat2985** [rytilahti/python-miio#316]
Where is the problem? Thank you.
```
% mirobo                                                                                                                            1 ↵
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 9, in <module>
    load_entry_point('python-miio==0.3.9', 'console_scripts', 'mirobo')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/miio/__init__.py", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_miio-0.3.9-py2.7.egg/miio/airconditioningcompanion.py", line 93
    def load_power(self) -> int:
                         ^
SyntaxError: invalid syntax
```

**Comment by rytilahti** [comment]
You are running way too old python version, the supported ones are 3.5+ and it is also defined in the setup.py file, so I'm curious how were you able to install it on python 2.7?

**Comment by renat2985** [comment]
Ok. I'm install Python 3.5.2+
Error: :(

```
% mirobo discover                                                                                                                     ✭
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netifaces!=0.10.5' distribution was not found and is required by zeroconf
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 20, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ImportError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netifaces!=0.10.5' distribution was not found and is required by zeroconf
```

```
% python3.5 -V                                                                                                                        ✭
Python 3.5.2+
```

```
vim /usr/local/bin/mirobo
  1 #!/usr/bin/python3.5
  2 # EASY-INSTALL-ENTRY-SCRIPT: 'python-miio==0.3.9','console_scripts','mirobo'
  3 __requires__ = 'python-miio==0.3.9'
  4 import sys
  5 from pkg_resources import load_entry_point
  6 
  7 if __name__ == '__main__':
  8     sys.exit(
  9         load_entry_point('python-miio==0.3.9', 'console_scripts', 'mirobo')()
 10     )
~          
```

**Comment by rytilahti** [comment]
Closing for inactivity, please reopen if this is still an issue, thanks!
