### ISSUE TITLE
Qing Mi Smart Power Strip cannot be setup，device id is 04b8824e

### ISSUE THREAD

**Issue by Goven** [rytilahti/python-miio#318]
Home Assistant release with the issue:

0.70.0b0

Last working Home Assistant release (if known):

none

Operating environment (Hass.io/Docker/Windows/etc.):

Docker

Component/platform:

device.py

Description of problem:

Qing Mi Smart Power Strip cannot be setup，device id is 04b8824e,may be it's a new type.

Problem-relevant configuration.yaml entries and (fill out even if it seems unimportant):

platform: xiaomi_miio
name: Qing Mi Smart Power Strip
host: 192.168.1.243
token: 6d282cbb8b376e69dba2175007486ec4
model: qmi.powerstrip.v1

Traceback (if applicable):

2018-05-19 11:24:44 ERROR (SyncWorker_6) [miio.protocol] unable to parse json '{"result":[
"on",50,58,"normal",6,,],"id":102}': Expecting value: line 1 column 34 (char 33)          
2018-05-19 11:24:44 ERROR (MainThread) [homeassistant.components.switch] xiaomi_miio: Erro
r on device update!                                                                       
Traceback (most recent call last):                                                        
  File "/usr/local/lib/python3.6/site-packages/miio/device.py", line 258, in send         
    data, addr = s.recvfrom(1024)                                                         
socket.timeout: timed out                                                                 
                                                                                          
During handling of the above exception, another exception occurred:                       
                                                                                          
Traceback (most recent call last):                                                        
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 244, in _async_add_en
tity                                                                                      
    await entity.async_device_update(warning=False)                                       
  File "/usr/src/app/homeassistant/helpers/entity.py", line 325, in async_device_update   
    yield from self.async_update()                                                        
  File "/usr/src/app/homeassistant/components/switch/xiaomi_miio.py", line 370, in async_u
pdate                                                                                     
    state = await self.hass.async_add_job(self._plug.status)   
File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run           
    result = self.fn(*self.args, **self.kwargs)                                           
  File "/usr/local/lib/python3.6/site-packages/miio/powerstrip.py", line 107, in status   
    properties                                                                            
  File "/usr/local/lib/python3.6/site-packages/miio/device.py", line 287, in send         
    return self.send(command, parameters, retry_count - 1)                                
  File "/usr/local/lib/python3.6/site-packages/miio/device.py", line 264, in send         
    self.__id = m.data.value["id"]                                                        
TypeError: 'NoneType' object is not subscriptable

**Comment by syssi** [comment]
The issue will be fixed in the upcoming release of python-miio.

cp. https://github.com/home-assistant/home-assistant/issues/13749

**Comment by Goven** [comment]
Thx
