### ISSUE TITLE
miplug status crash

### ISSUE THREAD

**Issue by Nixes** [rytilahti/python-miio#326]
getting a crash when I try to run the miplug status command on a Xiaomi Chuangmi Plug V3
```
/usr/local/lib/python3.5/dist-packages/miio/plug_cli.py:37: DeprecationWarning:                                             Call to deprecated class Plug (This device class is deprecated. Please use the C                                            huangmiPlug class in future and select a model by parameter 'model'.).
  dev = miio.Plug(ip, token, debug)
Traceback (most recent call last):
  File "/usr/local/bin/miplug", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/miio/click_common.py", line 47, i                                            n __call__
    return self.main(*args, **kwargs)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 697                                            , in main
    rv = self.invoke(ctx)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 106                                            6, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 895                                            , in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 535                                            , in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.5/site-packages/click/decorators.py", li                                            ne 59, in new_func
    obj = ctx.find_object(object_type)
  File "/home/username/.local/lib/python3.5/site-packages/click/core.py", line 447                                            , in find_object
    if isinstance(node.obj, object_type):
TypeError: isinstance() arg 2 must be a type or tuple of types

```

**Comment by Nixes** [comment]
actually nevermind, I see there is a closed issue for this, sorry for the noise.
