### ISSUE TITLE
TypeError: cleanup() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by giejay** [rytilahti/python-miio#386]
Hi,

I've got my robot (v1) working fine but every time I execute a command, which does work, its followed by an error. 

For example: 
mirobo zoned-clean [coordinates]
Cleaning zone(s) : ['ok']
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: cleanup() takes 1 positional argument but 2 were given

Do I need to upgrade my Python (3.5) or something?

**Comment by rytilahti** [comment]
Looks like here's a similar issue: https://github.com/rytilahti/python-eq3bt/issues/26 -- could you do `pip freeze|grep click` to see which version of click is installed? Maybe newer click versions have changed something.

**Comment by giejay** [comment]
Thanks for the fast response, pip3 uninstall Click and pip3 install Click==6.7 did the trick!
