### ISSUE TITLE
unsupported device zhimi airmonitor v1

### ISSUE THREAD

**Issue by cruig** [rytilahti/python-miio#393]
This is what happnd when I try discover

> WARNING:miio.discovery:Found unsupported device zhimi-airmonitor-v1

and 

> at 192.168.x.x, please report to developers

Are there different models? I thought it was normal for xiaomi devices to be called zhimi
This isn't a new model, should have been available for more than a year

I don't know what information I should gather. Please instruct me if I can help

**Comment by syssi** [comment]
Could you provide a product link? What's the product name?

**Comment by cruig** [comment]
@syssi I bought it from someone, here're some pictures and photos

![img_1150](https://user-images.githubusercontent.com/14120312/46905711-22b73780-cee7-11e8-801a-32c0395126dc.jpg)
![img_1151](https://user-images.githubusercontent.com/14120312/46905712-22b73780-cee7-11e8-817b-57b5e966b69e.jpg)
![img_1152](https://user-images.githubusercontent.com/14120312/46905713-234fce00-cee7-11e8-9e77-b263b5f8c2ee.jpg)

![img_1154](https://user-images.githubusercontent.com/14120312/46905714-23e86480-cee7-11e8-8387-f17c0b303f77.jpg)

It looks pretty standard, the name is 米家PM2.5检测仪, model JCY01ZM, CMIIT ID 2016DP6522
And I used the Mi Home app to connect it to my wifi

**Comment by syssi** [comment]
The device is already supported. Just the discovery is missing.

**Comment by cruig** [comment]
@syssi thanks, looking forward to the discovery

**Comment by cruig** [comment]
@syssi i just tried to clone the repo and `pip install` and `mirobo discover` again and got an exception:

> [mio@alarm python-miio]$ ~/.local/bin/mirobo discover
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
ERROR:miio.device:Unable to discover a device at address 192.168.1.200
Exception in thread zeroconf-ServiceBrowser__miio._udp.local.:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/home/mio/.local/lib/python3.7/site-packages/zeroconf.py", line 1382, in run
handler(self.zc)
File "/home/mio/.local/lib/python3.7/site-packages/zeroconf.py", line 1329, in <lambda>
state_change=state_change,
File "/home/mio/.local/lib/python3.7/site-packages/zeroconf.py", line 1235, in fire
h(**kwargs)
File "/home/mio/.local/lib/python3.7/site-packages/zeroconf.py", line 1302, in on_change
listener.add_service(*args)
File "/home/mio/.local/lib/python3.7/site-packages/miio/discovery.py", line 137, in add_service
dev = self.check_and_create_device(info, addr)
File "/home/mio/.local/lib/python3.7/site-packages/miio/discovery.py", line 120, in check_and_create_device
return create_device(name, addr, partial(v))
File "/home/mio/.local/lib/python3.7/site-packages/miio/discovery.py", line 99, in create_device
m = dev.do_discover()
File "/home/mio/.local/lib/python3.7/site-packages/miio/device.py", line 162, in do_discover
raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.1.200

**Comment by syssi** [comment]
Try to extract the token (https://python-miio.readthedocs.io/en/latest/discovery.html#tokens-from-backups) and communicate with the device:

```
miiocli airqualitymonitor --ip 192.168.1.200 --token token info
```

**Comment by cruig** [comment]
@syssi ok, i guess that needs to be done, though discover would be simpler to do

**Comment by syssi** [comment]
I assume the discovery want expose the token.

**Comment by scratcher28** [comment]
With `miiocli discover` I am getting:
miio.miioprotocol:  IP 192.168.1.200 (ID: 03c2391d) - token: b'00000000000000000000000000000000'

**Comment by scratcher28** [comment]
With `miiocli discover` I am getting:
miio.miioprotocol: IP 192.168.1.200 (ID: 03c2391d) - token: b'00000000000000000000000000000000'.
Any chance to fix it?
