### ISSUE TITLE
install-sound command not working on Xiaowa vacuum (roborock.vacuum.c1 v1.3.0)

### ISSUE THREAD

**Issue by andrei-khveras** [rytilahti/python-miio#418]
I was trying to execute the `install-sound` command against my Xiaowa cleaner (roborock.vacuum.c1 v1.3.0) and it resulted into the error as in log below.

I'd appreciate a lot if someone could get it resolved or give a confident confirmation that language packs uploading is not supported for given model.

```
mirobo -dd --ip=XXX --token=YYY install-sound ru_maxim_universal.pkg
INFO:miio.vacuum_cli:Debug mode active
DEBUG:miio.vacuum_cli:Read stored sequence ids: {'seq': 8, 'manual_seq': 0}
DEBUG:miio.vacuum_cli:Connecting to XXX with token YYY
Installing from ru_maxim_universal.pkg (md5: None) for id 10000
INFO:miio.updater:Serving on 0.0.0.0:41661, timeout 10
INFO:miio.updater:Using local ru_maxim_universal.pkg (md5: 46022838228679ffd598ec2b44a54b2d)
DEBUG:miio.updater:available interfaces: ['enp0s3']
DEBUG:miio.updater:Got addr: 192.168.0.104
Hosting file at http://192.168.0.104:41661/ru_maxim_universal.pkg
DEBUG:miio.protocol:Unable to decrypt, returning raw bytes: b''
DEBUG:miio.device:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x05vAx\x00\x00\x06E' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = b'\x05vAx' (total 4)
            ts = 1970-01-01 00:26:45
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
DEBUG:miio.device:Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x05vAx\x00\x00\x06E' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = b'\x05vAx' (total 4)
            ts = 1970-01-01 00:26:45
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' (total 16)
DEBUG:miio.device:Discovered 05764178 with ts: 1970-01-01 00:26:45, token: b'00000000000000000000000000000000'
DEBUG:miio.device:192.168.0.102:54321 >>: {'id': 9, 'method': 'dnld_install_sound', 'params': {'url': 'http://192.168.0.104:41661/ru_maxim_universal.pkg', 'md5': '46022838228679ffd598ec2b44a54b2d', 'sid': 10000}}
DEBUG:miio.device:send (timeout 5): Container: 
    data = Container: 
        data = b'>\xf6\xa6e\xdbxC\x93`,-%^\xa5]\xe8'... (truncated, total 176)
        value = {'id': 9, 'method': 'dnld_install_sound', 'params': {'url': 'http://192.168.0.104:41661/ru_maxim_universal.pkg', 'md5': '46022838228679ffd598ec2b44a54b2d', 'sid': 10000}}
        offset1 = 32
        offset2 = 208
        length = 176
    header = Container: 
        data = b'!1\x00\xd0\x00\x00\x00\x00\x05vAx\x00\x00\x06F' (total 16)
        value = Container: 
            length = 208
            unknown = 0
            device_id = b'\x05vAx' (total 4)
            ts = 1970-01-01 00:26:46
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xc6\xc0;\xa6\xd5\xd813\x89\xbc\xe1-\x0fP\xba\xa8' (total 16)
DEBUG:miio.device:recv from 192.168.0.102: Container: 
    data = Container: 
        data = b'Q\xe1\xaf\x8e\x14\xbf\n9\xcc\xb6\xa2\x00a\x1f\x8a\xef'... (truncated, total 32)
        value = {'result': ['OK'], 'id': 9}
        offset1 = 32
        offset2 = 64
        length = 32
    header = Container: 
        data = b'!1\x00@\x00\x00\x00\x00\x05vAx\x00\x00\x06F' (total 16)
        value = Container: 
            length = 64
            unknown = 0
            device_id = b'\x05vAx' (total 4)
            ts = 1970-01-01 00:26:46
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'V\x8f\xad\xb9\x12R\xcd\x81\x8f\xb3&7\x0b\x98\x1d\xb5' (total 16)
DEBUG:miio.device:192.168.0.102:54321 (ts: 1970-01-01 00:26:46, id: 9) << {'result': ['OK'], 'id': 9}
Traceback (most recent call last):
  File "/home/host/.local/bin/mirobo", line 11, in <module>
    load_entry_point('python-miio==0.4.3', 'console_scripts', 'mirobo')()
  File "/home/host/.local/lib/python3.6/site-packages/miio/click_common.py", line 54, in __call__
    return self.main(*args, **kwargs)
  File "/home/host/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/host/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/host/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/host/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/host/.local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/host/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/host/.local/lib/python3.6/site-packages/miio/vacuum_cli.py", line 483, in install_sound
    click.echo(vac.install_sound(local_url, md5sum, sid))
  File "/home/host/.local/lib/python3.6/site-packages/click/utils.py", line 222, in echo
    message = text_type(message)
  File "/home/host/.local/lib/python3.6/site-packages/miio/vacuumcontainers.py", line 484, in __repr__
    " - progress: %s>" % (self.sid, self.state,
  File "/home/host/.local/lib/python3.6/site-packages/miio/vacuumcontainers.py", line 464, in sid
    return self.data.get('sid_in_progress', None)
AttributeError: 'str' object has no attribute 'get'
ERROR:miio.updater:No request was made..
```

**Comment by MrRusch** [comment]
This does in fact work now on gen2. Pulled from master and sound packs now install.

**Comment by andrei-khveras** [comment]
@MrRusch please, check your vacuum model name. This request is about roborock.vacuum.c1 v1.3.0 and it doesn't support uploading language packs at the environmental level.
@rytilahti I believe this one can be closed at this point.
Thank you so much for your effort.
