### ISSUE TITLE
miio-extract-tokens raises a TypeError when running against extracted SQLite database

### ISSUE THREAD

**Issue by domibarton** [rytilahti/python-miio#467]
When running `miio-extract-tokens` against an extracted SQLite database from an iOS backup, the script raises a `TypeError`:

```
(homeassistant) root@rpi:/opt/homeassistant# miio-extract-tokens /tmp/1672094281_mihome.sqlite
INFO:miio.extract_tokens:Reading database from /tmp/1672094281_mihome.sqlite
INFO:miio.extract_tokens:Reading tokens from Apple DB
Traceback (most recent call last):
  File "/opt/homeassistant/homeassistant/bin/miio-extract-tokens", line 11, in <module>
    sys.exit(main())
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 155, in main
    devices = list(reader.read_tokens(backup))
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 113, in read_tokens
    yield from self.read_apple()
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 74, in read_apple
    token = BackupDatabaseReader.decrypt_ztoken(dev['ZTOKEN'])
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 50, in decrypt_ztoken
    if len(ztoken) <= 32:
TypeError: object of type 'NoneType' has no len()
```

Please note this is a follow up of the PR #460, as I want to leave issue-related discussions in the issue section.

I'll post more as soon as I've done some additional testing.

**Comment by domibarton** [comment]
@rytilahti I think I found the bug:

```
(homeassistant) root@rpi:/opt/homeassistant# miio-extract-tokens --dump-raw /tmp/1672094281_mihome.sqlite
…
INFO:miio.extract_tokens:{'ZADMINFLAG': 1,
 'ZBSSID': '',
 'ZDESC': 'Tap to connect',
 'ZDID': 'fimi.camera.c1_lanapcommondid',
 'ZEXTFWVERSION': None,
 'ZEXTISPWDENCRYPT': None,
 'ZEXTISSETPINCODE': None,
 'ZEXTKEYID': None,
 'ZEXTMCUVERSION': None,
 'ZEXTNEEDVERIFYCODE': None,
 'ZEXTP2PID': None,
 'ZEXTTOKEN': None,
 'ZISFROMSERVER': 0,
 'ZISONLINE': 1,
 'ZLATITUDE': 0.0,
 'ZLOCALIP': None,
 'ZLONGITUDE': 0.0,
 'ZMAC': '',
 'ZMODEL': 'fimi.camera.c1',
 'ZNAME': 'Mi Action Camera 4K(Hotspot direct connection)',
 'ZPARENT_ID': '',
 'ZPARENT_MODEL': '',
 'ZPERMITLEVEL': 0,
 'ZPID': 0,
 'ZRESETFLAG': 0,
 'ZRSSI': 0,
 'ZSHAREFLAG': 0,
 'ZSHOWMODE': 1,
 'ZSSID': '',
 'ZTOKEN': None,
 'ZTOKENENCRYPT': 1,
 'Z_ENT': 1,
 'Z_OPT': 1,
 'Z_PK': 7636}
Traceback (most recent call last):
  File "/opt/homeassistant/homeassistant/bin/miio-extract-tokens", line 11, in <module>
    sys.exit(main())
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 155, in main
    devices = list(reader.read_tokens(backup))
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 113, in read_tokens
    yield from self.read_apple()
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 74, in read_apple
    token = BackupDatabaseReader.decrypt_ztoken(dev['ZTOKEN'])
  File "/opt/homeassistant/homeassistant/lib/python3.5/site-packages/miio/extract_tokens.py", line 50, in decrypt_ztoken
    if len(ztoken) <= 32:
TypeError: object of type 'NoneType' has no len()
```

The action cam has only bluetooth connection, thus no token (`'ZTOKEN': None,`). I can have a look at the code and send a PR if you like.

**Comment by rytilahti** [comment]
Great! :+1: A PR is very welcome, I think the best way is simply to check for Noneness inside `decrypt_token`, that way those devices will still be listed in the output.

**Comment by domibarton** [comment]
> Great! 👍 A PR is very welcome, I think the best way is simply to check for Noneness inside `decrypt_token`, that way those devices will still be listed in the output.

Done, [that should work](https://github.com/rytilahti/python-miio/pull/469/files). I simply check for `None`ness as well and typecast it to a `str` before returning (in favour of `None`).

**Comment by rytilahti** [comment]
Thanks, this can be closed then!
