### ISSUE TITLE
Raise an exception on "unable to parse json"

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-miio#482]
```
2019-01-10 04:54:51 ERROR (Thread-11) [miio.protocol] unable to parse json '{"result":[net],"id":1960}': Expecting value: line 1 column 12 (char 11)
2019-01-10 04:54:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.philips_ambient_light fails

...

2019-01-10 04:54:51 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.philips_ambient_light fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 347, in async_device_update
    await self.async_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/light/xiaomi_miio.py", line 721, in async_update
    state = await self.hass.async_add_executor_job(self._light.status)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/miio/philips_eyecare.py", line 125, in status
    properties
  File "/srv/homeassistant/lib/python3.5/site-packages/miio/device.py", line 265, in send
    self.__id = m.data.value["id"]
TypeError: 'NoneType' object is not subscriptable
```
cp. https://github.com/home-assistant/home-assistant/issues/19906

**Comment by tedum11** [comment]
Dear syssi

Sorry to ask you here. I am looking forward to hearing your work for the xiaomi air monitoring(not pm2.5 product). Could i ask you the status of this development? I really appreciate it

**Comment by stevenroose** [comment]
I'm getting this error.. Is there a fix for this? I didn't used to get it with my robot.

```
$ mirobo --ip 192.168.8.1 --token 785a79774c434b4b4f594b476a533757 update-firmware ../output/vacuum_1910.pkg
Going to update from ../output/vacuum_1910.pkg
INFO:miio.updater:Serving on 0.0.0.0:41459, timeout 10
INFO:miio.updater:Using local ../output/vacuum_1910.pkg (md5: 0973be74c20c0316d244f033b3d97d6c)
Hosting file at http://192.168.8.39:41459/vacuum_1910.pkg
ERROR:miio.protocol:unable to parse json '': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/steven/software/rockrobo/flasher/venv/bin/mirobo", line 10, in <module>
    sys.exit(cli())
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/click_common.py", line 57, in __call__
    return self.main(*args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/vacuum_cli.py", line 609, in update_firmware
    update_res = vac.update(url, md5)
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/device.py", line 363, in update
    return self.send("miIO.ota", payload)[0] == "ok"
  File "/home/steven/software/rockrobo/flasher/venv/lib/python3.7/site-packages/miio/device.py", line 278, in send
    self.__id = m.data.value["id"]
TypeError: 'NoneType' object is not subscriptable
ERROR:miio.updater:No request was made..
```

**Comment by rezmus** [comment]
what's your current firmware?

**Comment by rytilahti** [comment]
It sounds like the initial handshake failed (i.e., the device did not respond to the request), indicating potential network issues. Are other commands working fine?

**Comment by Vertux** [comment]
@rytilahti  I have the same issue. The other mirobo commands like `info`, `status` etc. working fine
