### ISSUE TITLE
Add swing mode of a Chigo Air Conditioner

### ISSUE THREAD

**Issue by vaguecupid** [rytilahti/python-miio#518]
I have three xiaomi airconditioningcompanion, but one of them can't use after turning on the air conditioner. The error code is:

> 
2019-06-07 02:01:31 ERROR (MainThread) [homeassistant.components.climate] xiaomi_miio_airconditioningcompanion: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 276, in async_update
    ATTR_SWING_MODE: state.swing_mode.name.lower(),
  File "/usr/local/lib/python3.7/site-packages/miio/airconditioningcompanion.py", line 215, in swing_mode
    mode = int(self.state[5:6])
ValueError: invalid literal for int() with base 10: 'C'

**Comment by syssi** [comment]
Do you own different air conditions? Does the problematic one support special swing modes?

**Comment by vaguecupid** [comment]
> Do you own different air conditions? Does the problematic one support special swing modes?

I saw from the app, there is no difference between this and other in swing mode ,only on and off. Three air conditioners are of different brands(Panasonic,Midea,Chigo),The brand with problems is Chigo,

**Comment by syssi** [comment]
If you change the swing mode does the error change, too?

**Comment by vaguecupid** [comment]
yes, I turn off the swing mode,  and then restart hassio, the error code is:

> 019-06-07 03:38:00 ERROR (MainThread) [homeassistant.components.climate] xiaomi_miio_airconditioningcompanion: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/config/custom_components/xiaomi_miio_airconditioningcompanion/climate.py", line 276, in async_update
    ATTR_SWING_MODE: state.swing_mode.name.lower(),
  File "/usr/local/lib/python3.7/site-packages/miio/airconditioningcompanion.py", line 215, in swing_mode
    mode = int(self.state[5:6])
ValueError: invalid literal for int() with base 10: 'D'

**Comment by syssi** [comment]
Could you provide the output of the `status` commands? I'm interested in the value of `air_condition_model` (of the chigo).

**Comment by vaguecupid** [comment]
Thanks, The airconditioningcompanion can work perfectly

**Comment by syssi** [comment]
Could you provide the `air_condition_model` string nevertheless? It's important to improve the implementation.
