### ISSUE TITLE
Air Humidifier

### ISSUE THREAD

**Issue by flocc** [rytilahti/python-miio#529]
Hello, i have a problem here with Air humidifier:

>>> from miio import airhumidifier
>>> h = airhumidifier.AirHumidifierCA1("192.168.1.14", "********************************")
>>> h.info
<bound method Device.info of <miio.airhumidifier.AirHumidifierCA1 object at 0x7f6eed382668>>
>>> h.info()
zhimi.humidifier.ca1 v1.6.6 (04:CF:8C:87:11:5F) @ 192.168.1.14 - token: ********************************
>>> h.status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/miio/airhumidifier.py", line 232, in __repr__
    self.strong_mode_enabled,
  File "/usr/local/lib/python3.5/dist-packages/miio/airhumidifier.py", line 132, in strong_mode_enabled
    if self.firmware_version_minor == 25:
  File "/usr/local/lib/python3.5/dist-packages/miio/airhumidifier.py", line 153, in firmware_version_minor
    _, minor = self.firmware_version.rsplit('_', 1)
ValueError: not enough values to unpack (expected 2, got 1)

=====
while miiocli works good.

**Comment by syssi** [comment]
This is a bug. We are expecting a firmware version like this (format): 1.2.9_5033
