### ISSUE TITLE
subcon should be a Construct field

### ISSUE THREAD

**Issue by h4wkmoon** [rytilahti/python-miio#641]
Hi,
this is clearly a duplicate of another issue, but the original is locked.

Fresh install with pip3 : 

```
$ mirobo discover --handshake 1 
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 5, in <module>
    from mirobo.vacuum_cli import cli
  File "/usr/local/lib/python3.6/dist-packages/mirobo/__init__.py", line 2, in <module>
    from mirobo.protocol import Message, Utils
  File "/usr/local/lib/python3.6/dist-packages/mirobo/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "/home/fred/.local/lib/python3.6/site-packages/construct/core.py", line 2504, in __init__
    super(Const, self).__init__(subcon)
  File "/home/fred/.local/lib/python3.6/site-packages/construct/core.py", line 670, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
```

python_mirobo-0.2.0
construct-2.10.56
 

Am I missing something ?
Could you help me, plz ?

Regards,
Fred.

**Comment by rytilahti** [comment]
That is a very, very old version of mirobo. You should install `python-miio` instead, please reopen if that doesn't help!
