### ISSUE TITLE
Error while updating firmware

### ISSUE THREAD

**Issue by rabe21** [rytilahti/python-miio#664]
I was trying to run a firmware update on my S50. By running:

`mirobo --ip 192.168.1.183 --token xxxx update-firmware  ./v11_001886.fullos.pkg`

But unfortunately I  am getting constantly the following error message:
```
Going to update from ./v11_001886.fullos.pkg
INFO:miio.updater:Serving on 0.0.0.0:58859, timeout 10
INFO:miio.updater:Using local ./v11_001886.fullos.pkg (md5: 4f525cf7d326856ab9512612aaa9cbd8)
Hosting file at http://192.168.1.111:58859/v11_001886.fullos.pkg
ERROR:miio.protocol:unable to parse json '': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/mirobo", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/miio/vacuum_cli.py", line 609, in update_firmware
    update_res = vac.update(url, md5)
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 167, in update
    return self._protocol.send("miIO.ota", payload)[0] == "ok"
  File "/usr/local/lib/python3.7/site-packages/miio/miioprotocol.py", line 183, in send
    self.__id = m.data.value["id"]
TypeError: 'NoneType' object is not subscriptable
ERROR:miio.updater:No request was made..
```
The robot has a working WiFi and internet connection. Commands like `mirobo status` work without problems.

**Comment by rezmus** [comment]
if your current fw is not 3.3.9_X reset to factory firmware, then do ota.

**Comment by rabe21** [comment]
Thank you very much. After resetting the robot to factory settings it worked. Just out of curiosity is the reason known why higher versions don't work.

**Comment by rezmus** [comment]
with newer miio linux sdk they block local ota (using token).

**Comment by marcelrv** [comment]
Do you know what is blocked, the local download url or the command ?
If it is the latter, do you mean if I send the update request via the cloud to the vacuum it will still execute the request?

**Comment by rytilahti** [comment]
If you don't mind, could you also document this behavior in the docs? https://github.com/rytilahti/python-miio/blob/master/docs/troubleshooting.rst would be the file, thanks!
