### ISSUE TITLE
Error controlling gateway

### ISSUE THREAD

**Issue by serhatozkara** [rytilahti/python-miio#673]
miiocli gateway --ip 192.168.155.110 --token [TOKEN] info command (any gateway command) results in:

```Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 10, in <module>
    sys.exit(create_cli())
  File "/Library/Python/3.7/site-packages/miio/cli.py", line 44, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/Library/Python/3.7/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/3.7/site-packages/miio/click_common.py", line 242, in group_callback
    ctx.obj = self.device_class(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'debug'
```

**Comment by vers4ce** [comment]
Same with python 3.8 libraries

**Comment by rytilahti** [comment]
The linked PR should fix the issue, could you please test it?

**Comment by vers4ce** [comment]
tested it, works fine, thank you
