### ISSUE TITLE
STYJ02YM - AttributeError: 'ViomiVacuumStatus' object has no attribute 'mop_type'

### ISSUE THREAD

**Issue by Zaschii** [rytilahti/python-miio#704]
Hi all,
it seems that miiocli viomivacuum --ip 192.168.X.X --token XXXX info is working...

Model: viomi.vacuum.v7
Hardware version: Linux
Firmware version: 3.5.3_0047

But i get the following error with the status command....

miiocli viomivacuum --ip 192.168.X.X --token XXXX status

Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 44, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 285, in wrap
    result_msg = result_msg_fmt.format(**kwargs)
AttributeError: 'ViomiVacuumStatus' object has no attribute 'box_type'

BR

**Comment by rytilahti** [comment]
This will we fixed in the next release (#695).

**Comment by Zaschii** [comment]
Thanks... but next thing is the mop_type :-(...

after boy_type it seems that mop_type is also wrong or missing...

Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 44, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 285, in wrap
    result_msg = result_msg_fmt.format(**kwargs)
AttributeError: 'ViomiVacuumStatus' object has no attribute 'mop_type'

**Comment by rytilahti** [comment]
Ah, thanks for testing! The `mop_type` variable is not exposed at all, so for testing you could remove this line here: https://github.com/rytilahti/python-miio/blob/master/miio/viomivacuum.py#L207

**Comment by Zaschii** [comment]
Thanks for your quick reply... next missing value is water_level ;-)

Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 44, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 285, in wrap
    result_msg = result_msg_fmt.format(**kwargs)
AttributeError: 'ViomiVacuumStatus' object has no attribute 'water_level'

**Comment by Zaschii** [comment]
i removed water_level too and now status is working....

State: ViomiVacuumState.Docked
Mode: ViomiMode.Vacuum
Error: Unknown error None
Battery: 100
Fan speed: ViomiVacuumSpeed.Silent
Box type: ViomiBinType.Vacuum
Clean time: 0:00:00
Clean area: 1.1
Remember map: True
Has map: True
Has new map: False
Mop mode: ViomiMode.Vacuum

Thanks and BR

**Comment by Zaschii** [comment]
some other question... because iam too bad in python sorry :-).

How can i receive e.g. just the state from the viomistatus object.
As i can see the object is a zip with (properties, value).

e.g. the output of my small python script is just...
<miio.viomivacuum.ViomiVacuumStatus object at 0x7f38824fd668>

my python script
`
from miio import ViomiVacuum

vac = ViomiVacuum("192.168.X.X", "tokenXXXXXXX")

#properties
#           "run_state",
#            "mode",
#            "err_state",
#            "battary_life",
#            "box_type",
#            "mop_type",
#            "s_time",
#            "s_area",
#            "suction_grade",
#            "water_grade",
#            "remember_map",
#            "has_map",
#            "is_mop",
#            "has_newmap",

status_obj = vac.status()
print(status_obj)
`

**Comment by rytilahti** [comment]
Feel free to check out the PR (it should now display all information correctly, I hope).

To your question about accessing the state, all the elements in VacuumStatus class are properties, so you can do the following:
```
from miio import ViomiVacuum

vac = ViomiVacuum("192.168.X.X", "tokenXXXXXXX")

status_obj = vac.status()
print(status_obj.state)
```

**Comment by Zaschii** [comment]
thanks a lot... status output looks good...

State: ViomiVacuumState.Docked
Mode: ViomiMode.Vacuum
Error: Unknown error 2105
Battery: 100
Fan speed: ViomiVacuumSpeed.Silent
Box type: ViomiBinType.Vacuum
Mop type: 0
Clean time: 0:00:00
Clean area: 1.1
Water grade: ViomiWaterGrade.Medium
Remember map: True
Has map: True
Has new map: False
Mop mode: ViomiMode.Vacuum

**Comment by rytilahti** [comment]
Great, I think we can then merge it. Thanks for testing & reporting!
