### ISSUE TITLE
Viomi V8: AttributeError: 'NoneType' object has no attribute 'header'

### ISSUE THREAD

**Issue by tom2199** [rytilahti/python-miio#746]
Hello, if i'm trying to connect to my Mi Mop Pro (Viomi V8 with FW 3.5.3_0017) it connects maybe 5% of the time, 95% of the time i'm getting timeouts or the following error:
```
miiocli viomivacuum --ip 192.168.178.XXX --token 4XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXa info
Traceback (most recent call last):
  File "/home/user/.local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/home/user/.local/lib/python3.6/site-packages/miio/cli.py", line 44, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/home/user/.local/lib/python3.6/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/miio/device.py", line 182, in info
    return DeviceInfo(self.send("miIO.info"))
  File "/home/user/.local/lib/python3.6/site-packages/miio/device.py", line 147, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/home/user/.local/lib/python3.6/site-packages/miio/miioprotocol.py", line 150, in send
    self.send_handshake()
  File "/home/user/.local/lib/python3.6/site-packages/miio/miioprotocol.py", line 62, in send_handshake
    header = m.header.value
AttributeError: 'NoneType' object has no attribute 'header'
```

**Comment by rytilahti** [comment]
Try with the current git master, this issue should be fixed now thanks to #731 which will be part of the next upcoming release. Please reopen this if the current git master does not work and we can then figure out what's the problem.
