### ISSUE TITLE
set_waterflow roborock.vacuum.s5e

### ISSUE THREAD

**Issue by meteo88** [rytilahti/python-miio#786]
Hi,

i have an roborock.vacuum.s5e with installed python miio 0.5.3 - Version.
i wanted to change the Waterflow ( i get the same error when i want to get the actual waterflow with "waterflow" command),
but i only get an error:

` /usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token TOKEN set_waterflow 202
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 45, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 94, in convert
    return self.func(value)
TypeError: WaterFlow() takes no arguments
`

Best regards,
Dominik

**Comment by rytilahti** [comment]
Oops, looks like it wasn't defined as an enum like it should have been. Instead of using the number value for commands, you can also use the name in place of the enum value (so `set_waterflow high`, or `High`, should work just fine).

**Comment by meteo88** [comment]
Hi, sorry, with set_waterflow high or High it does not work either...

There is always the same error.

`/usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token TOKEN set_waterflow high
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 45, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 94, in convert
    return self.func(value)
TypeError: WaterFlow() takes no arguments`

OR
`/usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token 684734725a496670434c414251724f36 set_waterflow High
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 45, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/types.py", line 94, in convert
    return self.func(value)
TypeError: WaterFlow() takes no arguments
`

OR

`/usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token 684734725a496670434c414251724f36 waterflow
Running command waterflow
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 45, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 280, in wrap
    kwargs["result"] = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 245, in command_callback
    return miio_command.call(miio_device, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 193, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/vacuum.py", line 671, in waterflow
    return WaterFlow(self.send("get_water_box_custom_mode")[0])
TypeError: WaterFlow() takes no arguments
`

**Comment by rytilahti** [comment]
Are you running the current git master? I just merged that linked PR, so it should be fixed there (and will be fixed later on in the next release).

**Comment by meteo88** [comment]
I now updated the current git master.

The command "waterflow" is now working!

` /usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token TOKEN waterflow
Running command waterflow
WaterFlow.High
`

But the commands:
`/usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token TOKEN set_waterflow 201
Usage: miiocli vacuum set_waterflow [OPTIONS] WATERFLOW
Try 'miiocli vacuum set_waterflow --help' for help.

Error: Invalid value for 'WATERFLOW': 201
`

`/usr/local/bin/miiocli vacuum --ip 192.168.1.6 --token TOKENset_waterflow Minimum
Usage: miiocli vacuum set_waterflow [OPTIONS] WATERFLOW
Try 'miiocli vacuum set_waterflow --help' for help.

Error: Invalid value for 'WATERFLOW': Minimum
`

are not working.

do you know why?

Thank you !
Dominik

**Comment by meteo88** [comment]
Maybe there is a bug in the set_waterflow - function?

Getting the actual waterflow is working without problems, but setting it returns an error.

.......
`    @command()
    def waterflow(self) -> WaterFlow:
        """Get water flow setting."""
        return WaterFlow(self.send("get_water_box_custom_mode")[0])


@command(click.argument("waterflow", type=WaterFlow))
    def set_waterflow(self, waterflow: WaterFlow):
        """Set water flow setting."""
        return self.send("set_water_box_custom_mode", [waterflow.value])`
.......

**Comment by rytilahti** [comment]
Indeed, the cli tool should really get better tests to spot issues like this. The linked PR fixes that problem.

**Comment by meteo88** [comment]
Thanks for the quick fix, now everything is working!!
