### ISSUE TITLE
Getting devices list from Xiaomi Gateway 3 failed

### ISSUE THREAD

**Issue by oleg-l** [rytilahti/python-miio#807]
Hello!

Calling discover_devices() for Xiaomi Gateway 3 produces error.
 - OS: Ubuntu 18.04
 - python-miio: master, 0.5.3
 - Model: lumi.gateway.mgl03
 - Hardware version: Linux
 - Firmware version: 1.4.6_0012

Execute code to reproduce the behavior:

from miio import Gateway
gateway = Gateway("192.168.1.11", "********************************")
print("Info:")
print(gateway.info())
print("Devices:")
print(gateway.discover_devices())

Devices list expected but output is:

Info:
lumi.gateway.mgl03 v1.4.6_0012 (64:90:C1:7A:32:6B) @ 192.168.1.11 - token: ********************************
Devices:
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    print(gateway.discover_devices())
  File "/opt/oleg/prog/projects/miio/python-miio/miio/gateway.py", line 284, in discover_devices
    devices_raw = self.get_prop("device_list")
  File "/opt/oleg/prog/projects/miio/python-miio/miio/gateway.py", line 330, in get_prop
    return self.send("get_device_prop", ["lumi.0", property])
  File "/opt/oleg/prog/projects/miio/python-miio/miio/device.py", line 147, in send
    command, parameters, retry_count, extra_parameters=extra_parameters
  File "/opt/oleg/prog/projects/miio/python-miio/miio/miioprotocol.py", line 213, in send
    self._handle_error(payload["error"])
  File "/opt/oleg/prog/projects/miio/python-miio/miio/miioprotocol.py", line 273, in _handle_error
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -5015, 'message': 'device not found'}

**Comment by starkillerOG** [comment]
for future refrence:

> @oleg-l could you run the following python code and see what you get as a response:
> 
> ```
> from miio import Gateway
> 
> gateway = Gateway("192.168.1.IP", "TokenTokenToken")
> 
> print(gateway.send("get_device_list"))
> ```

> Hello @starkillerOG !
> Surely, I'll do my best.
> 
> The output of your script is:
> [{'did': 'lumi.158d000445dd37', 'model': 'lumi.sensor_ht.v1', 'num': 1, 'total': 1}]

**Comment by starkillerOG** [comment]
The output form the script looks good, based on that it is not that hard to add support for the `lumi.gateway.mgl03`

@oleg-l is it correct that you only have 1 temperature/humidity sensor connected to the gateway?

**Comment by oleg-l** [comment]
@starkillerOG Yes, it is correct

**Comment by starkillerOG** [comment]
@oleg-I I just made some code that schould make your gateway model work with subdevices.
Could you please try out this PR: https://github.com/rytilahti/python-miio/pull/782

**Comment by oleg-l** [comment]
@starkillerOG 

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    print(gateway.discover_devices())
  File "/opt/oleg/prog/projects/miio/python-miio-patch-17/miio/gateway/gateway.py", line 133, in discover_devices
    from .devices import SubDeviceInfo
  File "/opt/oleg/prog/projects/miio/python-miio-patch-17/miio/gateway/devices/__init__.py", line 4, in <module>
    from .cube import Cube, CubeV2
  File "/opt/oleg/prog/projects/miio/python-miio-patch-17/miio/gateway/devices/cube.py", line 3, in <module>
    from .subdevice import SubDevice
  File "/opt/oleg/prog/projects/miio/python-miio-patch-17/miio/gateway/devices/subdevice.py", line 12, in <module>
    from . import (
ImportError: cannot import name 'AqaraHT'

Am I missing something? Some requirements?

**Comment by starkillerOG** [comment]
@oleg-l I made a small change in the way the import is done.
maybe that will fix the issue, could you try it again?

Unfortunately I am moving and my equipment is in boxes so I cannot test it myself...

**Comment by oleg-l** [comment]
@starkillerOG I've pulled last changes from patch-17 but the result is the same.

**Comment by starkillerOG** [comment]
@oleg-l the '.' means import from __init__.py and in that file the imports to the correct files are specified, in this case weather_sensor.py for AqaraHT.

**Comment by starkillerOG** [comment]
@oleg-l I reverted to how the import was the last time I tested the code.
Could you give it another try?
If it does not work I need to wait untill my system is back up and running and I can test myself what the problem is with the imports

**Comment by oleg-l** [comment]
@starkillerOG Still the same

**Comment by starkillerOG** [comment]
@oleg-l this time I did some testing (withouth the actual gateway), I got the same import error as you.
I managed to fix the import error (it was in the order of importing things that gave a circular dependancy).
So it schould now work, at least it schould get further than before ;)

Could you do another test?

**Comment by starkillerOG** [comment]
@oleg-l I just made a commit that schould fix that error.
Could you try again?

**Comment by oleg-l** [comment]
@starkillerOG Great! It works!

Device list:
[{'did': 'lumi.158d000445dd37', 'model': 'lumi.sensor_ht.v1', 'num': 1, 'total': 1}]
Devices:
{'lumi.158d000445dd37': <Subdevice SensorHT: lumi.158d000445dd37, model: WSDCGQ01LM, zigbee: lumi.sensor_ht.v1, fw: -1, bat: None, vol: 3.025, props: {'temperature': None, 'humidity': None}>}

Now I'll try to build Home Assistant with patch-17 branch.

**Comment by starkillerOG** [comment]
@oleg-l great, it schould then work just fine with HomeAssistant.

Note that the values for the temperuture and humidity can be retrieved by running:

```
from miio import Gateway

gateway = Gateway("192.168.1.IP", "tokentokentoken")

gateway.discover_devices()
devices = gateway.devices

for dev in devices.values():
    dev.update()
    print(dev)
```

**Comment by AlexxIT** [comment]
My repo has a working code for getting a list of devices and their attributes using the miio protocol.
https://github.com/AlexxIT/XiaomiGateway3

**Comment by akimrx** [comment]
same issue occured

**Comment by starkillerOG** [comment]
@akimrx could you provide additional information and some logs.

**Comment by akimrx** [comment]
### Case
I have a gateway to which 3 temperature sensors (`miaomiaoce.sensor_ht.t2
`) are connected (BLE). The task is to get readings from these sensors.

### Some details
```
$ pip3 freeze | grep miio
python-miio==0.5.6
```

Only one method works normally - `info()` 

```
Model: lumi.gateway.mgl03
Hardware version: Linux
Firmware version: 1.5.0_0026
```

The other methods either work incorrectly or do not work at all

first:

```
from miio import Gateway

gateway = Gateway("10.0.0.34", "XXXXXX")

gateway.discover_devices()
devices = gateway.devices

for dev in devices.values():
    dev.update()
    print(dev)
```

result:
```
Traceback (most recent call last):
  File "gw-test.py", line 5, in <module>
    gateway.discover_devices()
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/miio/gateway/gateway.py", line 172, in discover_devices
    model_info = self.match_zigbee_model(device["model"], device["did"])
TypeError: string indices must be integers
```

the next thing I checked

```
print(gateway.send("get_device_list"))
```

the result is completely different from what I expected
```{'code': 0, 'id': 3, 'exe_time': 110}```

---

in addition the CLI interface itself is broken

```
$ miiocli gateway --help
Traceback (most recent call last):
  File "/Users/akimrx/xiaomi/bin/miiocli", line 10, in <module>
    sys.exit(create_cli())
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/miio/cli.py", line 63, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 950, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1137, in format_options
    self.format_commands(ctx, formatter)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1185, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/miio/click_common.py", line 253, in get_command
    ctx, self.device_pass(partial(self.command_callback, cmd))
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/miio/click_common.py", line 188, in wrap
    func = decorator(func)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/decorators.py", line 168, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1984, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 1483, in __init__
    param_decls or (), expose_value
  File "/Users/akimrx/xiaomi/lib/python3.7/site-packages/click/core.py", line 2019, in _parse_decls
    " {}".format(len(decls))
TypeError: Arguments take exactly one parameter declaration, got 2
```

---

cc @starkillerOG

**Comment by starkillerOG** [comment]
@akimrx the issue you have has already been resolved by this code: https://github.com/rytilahti/python-miio/blob/f2daab8d928fec1178ad6bd07009ab5ec953ac3a/miio/gateway/gateway.py#L173-L177

However there has not been a version release since that code was merged, so it is not yet included in version 0.5.6.

Basically the `gateway.send("get_device_list")` call will get the list of connected zigbee devices, since you do not have any, it returns some other messages instead of the list of devices. The code above catches that and will prevent an error.
However that does not change the fact that BLE devices as the once you have are not yet supported by this library.

You would need to figure out the correct command to get the list of BLE devices (if there even is such a command).

**Comment by balassy** [comment]
Hi,
Did you find the command to get the list of BLE devices?
Thanks.
