### ISSUE TITLE
viomivacuum doesn´t work with -o json_pretty

### ISSUE THREAD

**Issue by fs79** [rytilahti/python-miio#816]
/miiocli  -o json_pretty viomivacuum --ip x.x.x.x --token x1234567890x status
doesn´t work.
/miiocli  viomivacuum --ip x.x.x.x --token x1234567890x status

 - OS: Raspbian GNU/Linux 10 \n \l 
 - python-miio: miiocli, version 0.5.3

**Device information:**
It doesn´t work for the devicetype "viomivacuum".

1. execute the status command with flag "-o json_pretty"

**Expected behavior**
Should work, the same as for type "vacuum"

**Console output**
root@loxb01:~# **/usr/local/bin/miiocli  -o json_pretty viomivacuum --ip x.x.x.x --token x1234567890x status**
Traceback (most recent call last):
  File "/usr/local/bin/miiocli", line 8, in <module>
    sys.exit(create_cli())
  File "/usr/local/lib/python3.7/dist-packages/miio/cli.py", line 45, in create_cli
    return cli(auto_envvar_prefix="MIIO")
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 309, in wrap
    click.echo(json.dumps(result, indent=indent))
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} 
**TypeError: Object of type ViomiVacuumStatus is not JSON serializable**

**Comment by rytilahti** [comment]
This is happening because ViomiVacuumStatus does not have `__json__` method.

**Comment by fs79** [comment]
@rytilahti 
Ok. Who should implement?

**Comment by rytilahti** [comment]
@fs79 feel free to create a PR :-)
