### ISSUE TITLE
Issue with Xiaomi Miio gateway Integrations ZNDMWG03LM

### ISSUE THREAD

**Issue by a007007007csy** [rytilahti/python-miio#864]
**Describe the bug**
When I tried to add xiaomi_miio integration, no issue pop up.
But there was no new device or entity showed on the list which was connected to the gateway.
After that, I checked home-assistant.log, It showed issues.
Gateway's key and IP address were correctly submitted.

**Version information (please complete the following information):**
 - OS: 5.4.52 (x86)
 - python-miio: 0.5.3

**Device information:**
If the issue is specific to a device [Use `miiocli device --ip <ip address> --token <token>`]: THIS STEP CANNOT COMPELETE BECOUSE OF `ERROR: MISSING COMMAND`
  - Model: ZNDMWG03LM
  - Hardware version: unknown
  - Firmware version: 1.4.4_0003 (newest 1.4.5_0016)

**To Reproduce**
1. Add new integration, fill up correct ip and token, will be shown as adding successful.
2. There will be no new entity or device found
3. Hass's log will produce error about this gateway, every time restart hass service.

**Expected behavior**
The devices which connected to the gateway should be shown on the list.

**Console output**
```
2020-11-17 13:10:18 ERROR (SyncWorker_20) [miio.miioprotocol] Got error when receiving: timed out
2020-11-17 13:10:18 ERROR (MainThread) [homeassistant.components.xiaomi_miio.gateway] DeviceException during setup of xiaomi gateway with host 192.168.1.254
2020-11-17 13:10:39 ERROR (MainThread) [homeassistant.components.xiaomi_miio.gateway] DeviceException during setup of xiaomi gateway with host 192.168.1.254
2020-11-17 13:10:39 ERROR (MainThread) [homeassistant.components.xiaomi_miio.gateway] DeviceException during setup of xiaomi gateway with host 192.168.1.254
2020-11-17 14:08:34 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 119, in _handle_refresh_interval
await self.async_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 223, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 183, in state_attributes
forecast_entry[ATTR_FORECAST_TEMP],
KeyError: 'temperature'
```

**Comment by rezmus** [comment]
https://github.com/AlexxIT/XiaomiGateway3

**Comment by a007007007csy** [comment]
@rezmus Thank you for your useful information. By testing, my Xiaomi_gateway3, Zigbee devices, and BLE devices are all successfully connected to HA.
Additional information: If Xiaomi_gateway3's firmware is  v1.4.4_0003 (factory firmware) , please update once to make sure your gateway could working with ha and MiHome APP simultaneously!

**Comment by elenril2** [comment]
I have similar problem: [homeassistant.components.xiaomi_miio.gateway] DeviceException during setup of xiaomi gateway with host 192.168.1.IP with lumi.gateway.mgl03 gateway.
I'm using AlexxIT's component for Xiaomi Gateway 3 integration but I was counting that Xiaomi Miio will handle alarm modes (these features are not available in AlexxIT integration at the moment).
