### ISSUE TITLE
CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by DAVIZINH0** [rytilahti/python-miio#978]
I install today (19/03/2021) the python-miio and returns me a warning:

root@domoticz-oficial:/opt/domoticz# pip3 install -U python-miio                                                                       
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from
_bytes instead                                                                                                                         
  from cryptography.utils import int_from_bytes                                                                                        
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_byt
es instead                                                                                                                             
  from cryptography.utils import int_from_bytes 

some weeks ago this problem not ocurs, maybe some change?.

**Comment by DAVIZINH0** [comment]
this was solved by instaling this:
pip install pyyaml

But now when I launch the mirobo I have another problem:
root@domoticz-oficial:/opt/domoticz/userdata/scripts/personales/Xiaomi/IR# mirobo --ip '192.168.1.xxx' --token 'xxxxxxx' info                                                                                                                        
Traceback (most recent call last):                                                                                                     
  File "/usr/local/bin/mirobo", line 8, in <module>                                                                                    
    sys.exit(cli())                                                                                                                    
  File "/usr/local/lib/python3.7/dist-packages/miio/click_common.py", line 59, in __call__                                             
    return self.main(*args, **kwargs)                                                                                                  
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main                                                       
    rv = self.invoke(ctx)                                                                                                              
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1256, in invoke                                                    
    Command.invoke(self, ctx)                                                                                                          
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke                                                    
    return ctx.invoke(self.callback, **ctx.params)                                                                                     
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke                                                     
    return callback(*args, **kwargs)                                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func                                              
    return f(get_current_context(), *args, **kwargs)                                                                                   
  File "/usr/local/lib/python3.7/dist-packages/miio/vacuum_cli.py", line 61, in cli                                                    
    with open(id_file, "r") as f, contextlib.suppress(                                                                                 
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/python-miio/python-mirobo.seq'

**Comment by rytilahti** [comment]
The deprecation warning needs to be fixed so let's keep this issue open. The second issue is #972, I will release 0.5.5.1 to fix that in a moment.

**Comment by rytilahti** [comment]
The warning is coming from the library providing cryptographic primitives, so I don't think there's anything to fix here.
