### ISSUE TITLE
Roborock S7

### ISSUE THREAD

**Issue by Ciubas** [rytilahti/python-miio#989]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Roborock S7
  - Link: https://hejdom.pl/blog/11-xiaomi/465-odkurzacz-xiaomi-roborock-s7.html

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: roborock.vacuum.a15

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

What do you need to add this vaacum?

**Comment by vukisz** [comment]
@rytilahti 
I am getting this error, as mentioned in https://github.com/home-assistant/core/issues/43836
```
2021-03-25 18:04:51 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/.bIncludes/google_assistant.yaml contains duplicate key "switch.boileris". Check lines 29 and 34
2021-03-25 18:04:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-25 18:04:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-25 18:04:59 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.xiaomi_miio
2021-03-25 18:05:01 ERROR (MainThread) [homeassistant.components.vacuum] xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/vacuum.py", line 499, in update
    self.last_clean = self._device.last_clean_details()
  File "/usr/local/lib/python3.8/site-packages/miio/vacuum.py", line 352, in last_clean_details
    if not history.ids:
  File "/usr/local/lib/python3.8/site-packages/miio/vacuumcontainers.py", line 219, in ids
    return list(self.data[3])
KeyError: 3
```

I tried adding debug logs with following config:
```
# Logger =>
logger:
  default: critical
  logs:
    homeassistant.components.vacuum: debug
# Logger <=
```

But I still cannot find any additional logs. Is this config correct? If so where I should search for the output?

Integration SS:
![image](https://user-images.githubusercontent.com/48272340/112505934-eebded00-8d95-11eb-825d-af4a0a95b948.png)

**Comment by rezmus** [comment]
it's a new model, 2nd model of roborock which deploys new miotspec protocol. you should search for HA integration that supports s4 max model (a19). s7 should be very similar. if there isn't any just wait till someone adds support.

**Comment by rytilahti** [comment]
Maybe the device sports both miio and miot support? Anyway, if the linked PR fixes this, homeassistant should have at least basic support for the device at some point out of the box.

**Comment by rezmus** [comment]
@rytilahti it's possible. afair new viomi with miotspec also supports old miio cmds, at least some.

**Comment by vukisz** [comment]
Will this be available with next HA update?
